// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compute/v1/common.proto

// dc2 Service
//
// dc2 Service API consists of a single service which returns
// a message.

package compute

import (
	context "context"
	fmt "fmt"
	v1 "github.com/didiyun/didiyun-go-sdk/base/v1"
	_ "github.com/didiyun/didiyun-go-sdk/bill/v1"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dc2Info struct {
	Dc2Uuid              string         `protobuf:"bytes,1,opt,name=dc2Uuid,proto3" json:"dc2Uuid,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           int64          `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64          `protobuf:"varint,4,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Ip                   string         `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Status               string         `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	OsType               string         `protobuf:"bytes,7,opt,name=osType,proto3" json:"osType,omitempty"`
	Platform             string         `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
	ImgUuid              string         `protobuf:"bytes,9,opt,name=imgUuid,proto3" json:"imgUuid,omitempty"`
	ImgId                string         `protobuf:"bytes,10,opt,name=imgId,proto3" json:"imgId,omitempty"`
	Dc2Tags              []string       `protobuf:"bytes,11,rep,name=dc2Tags,proto3" json:"dc2Tags,omitempty"`
	Job                  *v1.JobInfo    `protobuf:"bytes,12,opt,name=job,proto3" json:"job,omitempty"`
	Eip                  *EipInfo       `protobuf:"bytes,13,opt,name=eip,proto3" json:"eip,omitempty"`
	Ebs                  []*EbsInfo     `protobuf:"bytes,14,rep,name=ebs,proto3" json:"ebs,omitempty"`
	Region               *v1.RegionInfo `protobuf:"bytes,15,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Dc2Info) Reset()         { *m = Dc2Info{} }
func (m *Dc2Info) String() string { return proto.CompactTextString(m) }
func (*Dc2Info) ProtoMessage()    {}
func (*Dc2Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{0}
}

func (m *Dc2Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dc2Info.Unmarshal(m, b)
}
func (m *Dc2Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dc2Info.Marshal(b, m, deterministic)
}
func (m *Dc2Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dc2Info.Merge(m, src)
}
func (m *Dc2Info) XXX_Size() int {
	return xxx_messageInfo_Dc2Info.Size(m)
}
func (m *Dc2Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Dc2Info.DiscardUnknown(m)
}

var xxx_messageInfo_Dc2Info proto.InternalMessageInfo

func (m *Dc2Info) GetDc2Uuid() string {
	if m != nil {
		return m.Dc2Uuid
	}
	return ""
}

func (m *Dc2Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dc2Info) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Dc2Info) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Dc2Info) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Dc2Info) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Dc2Info) GetOsType() string {
	if m != nil {
		return m.OsType
	}
	return ""
}

func (m *Dc2Info) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Dc2Info) GetImgUuid() string {
	if m != nil {
		return m.ImgUuid
	}
	return ""
}

func (m *Dc2Info) GetImgId() string {
	if m != nil {
		return m.ImgId
	}
	return ""
}

func (m *Dc2Info) GetDc2Tags() []string {
	if m != nil {
		return m.Dc2Tags
	}
	return nil
}

func (m *Dc2Info) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *Dc2Info) GetEip() *EipInfo {
	if m != nil {
		return m.Eip
	}
	return nil
}

func (m *Dc2Info) GetEbs() []*EbsInfo {
	if m != nil {
		return m.Ebs
	}
	return nil
}

func (m *Dc2Info) GetRegion() *v1.RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

type EipInfo struct {
	Ip                   string         `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	EipUuid              string         `protobuf:"bytes,2,opt,name=eipUuid,proto3" json:"eipUuid,omitempty"`
	EipTags              []string       `protobuf:"bytes,3,rep,name=eipTags,proto3" json:"eipTags,omitempty"`
	Status               string         `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Region               *v1.RegionInfo `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	CreateTime           int64          `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64          `protobuf:"varint,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Dc2                  *Dc2Info       `protobuf:"bytes,8,opt,name=dc2,proto3" json:"dc2,omitempty"`
	Job                  *v1.JobInfo    `protobuf:"bytes,9,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EipInfo) Reset()         { *m = EipInfo{} }
func (m *EipInfo) String() string { return proto.CompactTextString(m) }
func (*EipInfo) ProtoMessage()    {}
func (*EipInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{1}
}

func (m *EipInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EipInfo.Unmarshal(m, b)
}
func (m *EipInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EipInfo.Marshal(b, m, deterministic)
}
func (m *EipInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EipInfo.Merge(m, src)
}
func (m *EipInfo) XXX_Size() int {
	return xxx_messageInfo_EipInfo.Size(m)
}
func (m *EipInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EipInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EipInfo proto.InternalMessageInfo

func (m *EipInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *EipInfo) GetEipUuid() string {
	if m != nil {
		return m.EipUuid
	}
	return ""
}

func (m *EipInfo) GetEipTags() []string {
	if m != nil {
		return m.EipTags
	}
	return nil
}

func (m *EipInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EipInfo) GetRegion() *v1.RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *EipInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *EipInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *EipInfo) GetDc2() *Dc2Info {
	if m != nil {
		return m.Dc2
	}
	return nil
}

func (m *EipInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

type EbsInfo struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EbsUuid              string                `protobuf:"bytes,2,opt,name=ebsUuid,proto3" json:"ebsUuid,omitempty"`
	Type                 string                `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Attr                 string                `protobuf:"bytes,4,opt,name=attr,proto3" json:"attr,omitempty"`
	EbsTags              []string              `protobuf:"bytes,5,rep,name=ebsTags,proto3" json:"ebsTags,omitempty"`
	Region               *v1.RegionAndZoneInfo `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	DeviceName           string                `protobuf:"bytes,7,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	CreateTime           int64                 `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64                 `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Job                  *v1.JobInfo           `protobuf:"bytes,10,opt,name=job,proto3" json:"job,omitempty"`
	Dc2                  *Dc2Info              `protobuf:"bytes,11,opt,name=dc2,proto3" json:"dc2,omitempty"`
	Size                 int64                 `protobuf:"varint,12,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EbsInfo) Reset()         { *m = EbsInfo{} }
func (m *EbsInfo) String() string { return proto.CompactTextString(m) }
func (*EbsInfo) ProtoMessage()    {}
func (*EbsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{2}
}

func (m *EbsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EbsInfo.Unmarshal(m, b)
}
func (m *EbsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EbsInfo.Marshal(b, m, deterministic)
}
func (m *EbsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EbsInfo.Merge(m, src)
}
func (m *EbsInfo) XXX_Size() int {
	return xxx_messageInfo_EbsInfo.Size(m)
}
func (m *EbsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EbsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EbsInfo proto.InternalMessageInfo

func (m *EbsInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EbsInfo) GetEbsUuid() string {
	if m != nil {
		return m.EbsUuid
	}
	return ""
}

func (m *EbsInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EbsInfo) GetAttr() string {
	if m != nil {
		return m.Attr
	}
	return ""
}

func (m *EbsInfo) GetEbsTags() []string {
	if m != nil {
		return m.EbsTags
	}
	return nil
}

func (m *EbsInfo) GetRegion() *v1.RegionAndZoneInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *EbsInfo) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *EbsInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *EbsInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *EbsInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *EbsInfo) GetDc2() *Dc2Info {
	if m != nil {
		return m.Dc2
	}
	return nil
}

func (m *EbsInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SlbInfo struct {
	SlbUuid              string         `protobuf:"bytes,1,opt,name=slbUuid,proto3" json:"slbUuid,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string         `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	WafStatus            string         `protobuf:"bytes,4,opt,name=wafStatus,proto3" json:"wafStatus,omitempty"`
	CreateTime           int64          `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64          `protobuf:"varint,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Beip                 *BeipInfo      `protobuf:"bytes,7,opt,name=beip,proto3" json:"beip,omitempty"`
	Vpc                  *VpcInfo       `protobuf:"bytes,8,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Flow                 *FlowInfo      `protobuf:"bytes,9,opt,name=flow,proto3" json:"flow,omitempty"`
	SepcInfo             *SpecInfo      `protobuf:"bytes,10,opt,name=SepcInfo,proto3" json:"SepcInfo,omitempty"`
	Region               *v1.RegionInfo `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	Job                  *v1.JobInfo    `protobuf:"bytes,12,opt,name=job,proto3" json:"job,omitempty"`
	SlbTags              []string       `protobuf:"bytes,13,rep,name=slbTags,proto3" json:"slbTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SlbInfo) Reset()         { *m = SlbInfo{} }
func (m *SlbInfo) String() string { return proto.CompactTextString(m) }
func (*SlbInfo) ProtoMessage()    {}
func (*SlbInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{3}
}

func (m *SlbInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlbInfo.Unmarshal(m, b)
}
func (m *SlbInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlbInfo.Marshal(b, m, deterministic)
}
func (m *SlbInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlbInfo.Merge(m, src)
}
func (m *SlbInfo) XXX_Size() int {
	return xxx_messageInfo_SlbInfo.Size(m)
}
func (m *SlbInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SlbInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SlbInfo proto.InternalMessageInfo

func (m *SlbInfo) GetSlbUuid() string {
	if m != nil {
		return m.SlbUuid
	}
	return ""
}

func (m *SlbInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SlbInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SlbInfo) GetWafStatus() string {
	if m != nil {
		return m.WafStatus
	}
	return ""
}

func (m *SlbInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SlbInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SlbInfo) GetBeip() *BeipInfo {
	if m != nil {
		return m.Beip
	}
	return nil
}

func (m *SlbInfo) GetVpc() *VpcInfo {
	if m != nil {
		return m.Vpc
	}
	return nil
}

func (m *SlbInfo) GetFlow() *FlowInfo {
	if m != nil {
		return m.Flow
	}
	return nil
}

func (m *SlbInfo) GetSepcInfo() *SpecInfo {
	if m != nil {
		return m.SepcInfo
	}
	return nil
}

func (m *SlbInfo) GetRegion() *v1.RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *SlbInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *SlbInfo) GetSlbTags() []string {
	if m != nil {
		return m.SlbTags
	}
	return nil
}

type BeipInfo struct {
	BeipUuid             string   `protobuf:"bytes,1,opt,name=beipUuid,proto3" json:"beipUuid,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,4,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeipInfo) Reset()         { *m = BeipInfo{} }
func (m *BeipInfo) String() string { return proto.CompactTextString(m) }
func (*BeipInfo) ProtoMessage()    {}
func (*BeipInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{4}
}

func (m *BeipInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeipInfo.Unmarshal(m, b)
}
func (m *BeipInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeipInfo.Marshal(b, m, deterministic)
}
func (m *BeipInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeipInfo.Merge(m, src)
}
func (m *BeipInfo) XXX_Size() int {
	return xxx_messageInfo_BeipInfo.Size(m)
}
func (m *BeipInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BeipInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BeipInfo proto.InternalMessageInfo

func (m *BeipInfo) GetBeipUuid() string {
	if m != nil {
		return m.BeipUuid
	}
	return ""
}

func (m *BeipInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BeipInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *BeipInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type FlowInfo struct {
	In                   float32  `protobuf:"fixed32,1,opt,name=in,proto3" json:"in,omitempty"`
	Out                  float32  `protobuf:"fixed32,2,opt,name=out,proto3" json:"out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowInfo) Reset()         { *m = FlowInfo{} }
func (m *FlowInfo) String() string { return proto.CompactTextString(m) }
func (*FlowInfo) ProtoMessage()    {}
func (*FlowInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{5}
}

func (m *FlowInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowInfo.Unmarshal(m, b)
}
func (m *FlowInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowInfo.Marshal(b, m, deterministic)
}
func (m *FlowInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowInfo.Merge(m, src)
}
func (m *FlowInfo) XXX_Size() int {
	return xxx_messageInfo_FlowInfo.Size(m)
}
func (m *FlowInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FlowInfo proto.InternalMessageInfo

func (m *FlowInfo) GetIn() float32 {
	if m != nil {
		return m.In
	}
	return 0
}

func (m *FlowInfo) GetOut() float32 {
	if m != nil {
		return m.Out
	}
	return 0
}

type SpecInfo struct {
	OfferingUuid         string   `protobuf:"bytes,1,opt,name=offeringUuid,proto3" json:"offeringUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpecInfo) Reset()         { *m = SpecInfo{} }
func (m *SpecInfo) String() string { return proto.CompactTextString(m) }
func (*SpecInfo) ProtoMessage()    {}
func (*SpecInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{6}
}

func (m *SpecInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecInfo.Unmarshal(m, b)
}
func (m *SpecInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecInfo.Marshal(b, m, deterministic)
}
func (m *SpecInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecInfo.Merge(m, src)
}
func (m *SpecInfo) XXX_Size() int {
	return xxx_messageInfo_SpecInfo.Size(m)
}
func (m *SpecInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SpecInfo proto.InternalMessageInfo

func (m *SpecInfo) GetOfferingUuid() string {
	if m != nil {
		return m.OfferingUuid
	}
	return ""
}

type SnapInfo struct {
	SnapUuid             string         `protobuf:"bytes,1,opt,name=snapUuid,proto3" json:"snapUuid,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CanBeReverted        bool           `protobuf:"varint,3,opt,name=canBeReverted,proto3" json:"canBeReverted,omitempty"`
	IsGeneral            bool           `protobuf:"varint,4,opt,name=isGeneral,proto3" json:"isGeneral,omitempty"`
	CreateTime           int64          `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64          `protobuf:"varint,6,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Size                 int64          `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Type                 string         `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Dc2                  *Dc2Info       `protobuf:"bytes,9,opt,name=dc2,proto3" json:"dc2,omitempty"`
	Ebs                  *EbsInfo       `protobuf:"bytes,10,opt,name=ebs,proto3" json:"ebs,omitempty"`
	Region               *v1.RegionInfo `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	Job                  *v1.JobInfo    `protobuf:"bytes,12,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SnapInfo) Reset()         { *m = SnapInfo{} }
func (m *SnapInfo) String() string { return proto.CompactTextString(m) }
func (*SnapInfo) ProtoMessage()    {}
func (*SnapInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{7}
}

func (m *SnapInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapInfo.Unmarshal(m, b)
}
func (m *SnapInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapInfo.Marshal(b, m, deterministic)
}
func (m *SnapInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapInfo.Merge(m, src)
}
func (m *SnapInfo) XXX_Size() int {
	return xxx_messageInfo_SnapInfo.Size(m)
}
func (m *SnapInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SnapInfo proto.InternalMessageInfo

func (m *SnapInfo) GetSnapUuid() string {
	if m != nil {
		return m.SnapUuid
	}
	return ""
}

func (m *SnapInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SnapInfo) GetCanBeReverted() bool {
	if m != nil {
		return m.CanBeReverted
	}
	return false
}

func (m *SnapInfo) GetIsGeneral() bool {
	if m != nil {
		return m.IsGeneral
	}
	return false
}

func (m *SnapInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SnapInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SnapInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SnapInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SnapInfo) GetDc2() *Dc2Info {
	if m != nil {
		return m.Dc2
	}
	return nil
}

func (m *SnapInfo) GetEbs() *EbsInfo {
	if m != nil {
		return m.Ebs
	}
	return nil
}

func (m *SnapInfo) GetRegion() *v1.RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *SnapInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

type VpcInfo struct {
	VpcUuid              string         `protobuf:"bytes,1,opt,name=vpcUuid,proto3" json:"vpcUuid,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           int64          `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64          `protobuf:"varint,4,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	IsDefault            bool           `protobuf:"varint,5,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Cidr                 string         `protobuf:"bytes,6,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Region               *v1.RegionInfo `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Job                  *v1.JobInfo    `protobuf:"bytes,8,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *VpcInfo) Reset()         { *m = VpcInfo{} }
func (m *VpcInfo) String() string { return proto.CompactTextString(m) }
func (*VpcInfo) ProtoMessage()    {}
func (*VpcInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{8}
}

func (m *VpcInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VpcInfo.Unmarshal(m, b)
}
func (m *VpcInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VpcInfo.Marshal(b, m, deterministic)
}
func (m *VpcInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VpcInfo.Merge(m, src)
}
func (m *VpcInfo) XXX_Size() int {
	return xxx_messageInfo_VpcInfo.Size(m)
}
func (m *VpcInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VpcInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VpcInfo proto.InternalMessageInfo

func (m *VpcInfo) GetVpcUuid() string {
	if m != nil {
		return m.VpcUuid
	}
	return ""
}

func (m *VpcInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VpcInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *VpcInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *VpcInfo) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *VpcInfo) GetCidr() string {
	if m != nil {
		return m.Cidr
	}
	return ""
}

func (m *VpcInfo) GetRegion() *v1.RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *VpcInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

type SubnetInfo struct {
	SubnetUuid           string       `protobuf:"bytes,1,opt,name=subnetUuid,proto3" json:"subnetUuid,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           int64        `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64        `protobuf:"varint,4,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	IsDefault            bool         `protobuf:"varint,5,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Cidr                 string       `protobuf:"bytes,6,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Zone                 *v1.ZoneInfo `protobuf:"bytes,7,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubnetInfo) Reset()         { *m = SubnetInfo{} }
func (m *SubnetInfo) String() string { return proto.CompactTextString(m) }
func (*SubnetInfo) ProtoMessage()    {}
func (*SubnetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{9}
}

func (m *SubnetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubnetInfo.Unmarshal(m, b)
}
func (m *SubnetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubnetInfo.Marshal(b, m, deterministic)
}
func (m *SubnetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetInfo.Merge(m, src)
}
func (m *SubnetInfo) XXX_Size() int {
	return xxx_messageInfo_SubnetInfo.Size(m)
}
func (m *SubnetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetInfo proto.InternalMessageInfo

func (m *SubnetInfo) GetSubnetUuid() string {
	if m != nil {
		return m.SubnetUuid
	}
	return ""
}

func (m *SubnetInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SubnetInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SubnetInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SubnetInfo) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *SubnetInfo) GetCidr() string {
	if m != nil {
		return m.Cidr
	}
	return ""
}

func (m *SubnetInfo) GetZone() *v1.ZoneInfo {
	if m != nil {
		return m.Zone
	}
	return nil
}

type TotalCntInfo struct {
	TotalCnt             int32    `protobuf:"varint,1,opt,name=totalCnt,proto3" json:"totalCnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalCntInfo) Reset()         { *m = TotalCntInfo{} }
func (m *TotalCntInfo) String() string { return proto.CompactTextString(m) }
func (*TotalCntInfo) ProtoMessage()    {}
func (*TotalCntInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{10}
}

func (m *TotalCntInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalCntInfo.Unmarshal(m, b)
}
func (m *TotalCntInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalCntInfo.Marshal(b, m, deterministic)
}
func (m *TotalCntInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalCntInfo.Merge(m, src)
}
func (m *TotalCntInfo) XXX_Size() int {
	return xxx_messageInfo_TotalCntInfo.Size(m)
}
func (m *TotalCntInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalCntInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TotalCntInfo proto.InternalMessageInfo

func (m *TotalCntInfo) GetTotalCnt() int32 {
	if m != nil {
		return m.TotalCnt
	}
	return 0
}

type SgInfo struct {
	SgUuid               string         `protobuf:"bytes,1,opt,name=sgUuid,proto3" json:"sgUuid,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           int64          `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64          `protobuf:"varint,4,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	IsDefault            bool           `protobuf:"varint,5,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Dc2Cnt               int64          `protobuf:"varint,6,opt,name=dc2Cnt,proto3" json:"dc2Cnt,omitempty"`
	SgRuleCnt            int64          `protobuf:"varint,7,opt,name=sgRuleCnt,proto3" json:"sgRuleCnt,omitempty"`
	Vpc                  *VpcInfo       `protobuf:"bytes,8,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Region               *v1.RegionInfo `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	Job                  *v1.JobInfo    `protobuf:"bytes,10,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SgInfo) Reset()         { *m = SgInfo{} }
func (m *SgInfo) String() string { return proto.CompactTextString(m) }
func (*SgInfo) ProtoMessage()    {}
func (*SgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{11}
}

func (m *SgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SgInfo.Unmarshal(m, b)
}
func (m *SgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SgInfo.Marshal(b, m, deterministic)
}
func (m *SgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SgInfo.Merge(m, src)
}
func (m *SgInfo) XXX_Size() int {
	return xxx_messageInfo_SgInfo.Size(m)
}
func (m *SgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SgInfo proto.InternalMessageInfo

func (m *SgInfo) GetSgUuid() string {
	if m != nil {
		return m.SgUuid
	}
	return ""
}

func (m *SgInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SgInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SgInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SgInfo) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *SgInfo) GetDc2Cnt() int64 {
	if m != nil {
		return m.Dc2Cnt
	}
	return 0
}

func (m *SgInfo) GetSgRuleCnt() int64 {
	if m != nil {
		return m.SgRuleCnt
	}
	return 0
}

func (m *SgInfo) GetVpc() *VpcInfo {
	if m != nil {
		return m.Vpc
	}
	return nil
}

func (m *SgInfo) GetRegion() *v1.RegionInfo {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *SgInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

type SgRuleInfo struct {
	SgRuleUuid           string      `protobuf:"bytes,1,opt,name=sgRuleUuid,proto3" json:"sgRuleUuid,omitempty"`
	CreateTime           int64       `protobuf:"varint,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64       `protobuf:"varint,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Type                 string      `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Protocol             string      `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	StartPort            int64       `protobuf:"varint,6,opt,name=startPort,proto3" json:"startPort,omitempty"`
	EndPort              int64       `protobuf:"varint,7,opt,name=endPort,proto3" json:"endPort,omitempty"`
	AllowedCidr          string      `protobuf:"bytes,8,opt,name=allowedCidr,proto3" json:"allowedCidr,omitempty"`
	IsDefault            bool        `protobuf:"varint,9,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Sg                   *SgInfo     `protobuf:"bytes,10,opt,name=sg,proto3" json:"sg,omitempty"`
	Vpc                  *VpcInfo    `protobuf:"bytes,11,opt,name=vpc,proto3" json:"vpc,omitempty"`
	Job                  *v1.JobInfo `protobuf:"bytes,12,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SgRuleInfo) Reset()         { *m = SgRuleInfo{} }
func (m *SgRuleInfo) String() string { return proto.CompactTextString(m) }
func (*SgRuleInfo) ProtoMessage()    {}
func (*SgRuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{12}
}

func (m *SgRuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SgRuleInfo.Unmarshal(m, b)
}
func (m *SgRuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SgRuleInfo.Marshal(b, m, deterministic)
}
func (m *SgRuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SgRuleInfo.Merge(m, src)
}
func (m *SgRuleInfo) XXX_Size() int {
	return xxx_messageInfo_SgRuleInfo.Size(m)
}
func (m *SgRuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SgRuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SgRuleInfo proto.InternalMessageInfo

func (m *SgRuleInfo) GetSgRuleUuid() string {
	if m != nil {
		return m.SgRuleUuid
	}
	return ""
}

func (m *SgRuleInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SgRuleInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SgRuleInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SgRuleInfo) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *SgRuleInfo) GetStartPort() int64 {
	if m != nil {
		return m.StartPort
	}
	return 0
}

func (m *SgRuleInfo) GetEndPort() int64 {
	if m != nil {
		return m.EndPort
	}
	return 0
}

func (m *SgRuleInfo) GetAllowedCidr() string {
	if m != nil {
		return m.AllowedCidr
	}
	return ""
}

func (m *SgRuleInfo) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *SgRuleInfo) GetSg() *SgInfo {
	if m != nil {
		return m.Sg
	}
	return nil
}

func (m *SgRuleInfo) GetVpc() *VpcInfo {
	if m != nil {
		return m.Vpc
	}
	return nil
}

func (m *SgRuleInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

type CportInfo struct {
	CportUuid            string      `protobuf:"bytes,1,opt,name=cportUuid,proto3" json:"cportUuid,omitempty"`
	Ip                   string      `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	ContainerId          string      `protobuf:"bytes,3,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Mac                  string      `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	Netmask              string      `protobuf:"bytes,5,opt,name=netmask,proto3" json:"netmask,omitempty"`
	PodName              string      `protobuf:"bytes,6,opt,name=podName,proto3" json:"podName,omitempty"`
	PodNs                string      `protobuf:"bytes,7,opt,name=podNs,proto3" json:"podNs,omitempty"`
	VmNicUuid            string      `protobuf:"bytes,8,opt,name=vmNicUuid,proto3" json:"vmNicUuid,omitempty"`
	Gateway              string      `protobuf:"bytes,9,opt,name=gateway,proto3" json:"gateway,omitempty"`
	CreateTime           int64       `protobuf:"varint,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64       `protobuf:"varint,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Job                  *v1.JobInfo `protobuf:"bytes,12,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CportInfo) Reset()         { *m = CportInfo{} }
func (m *CportInfo) String() string { return proto.CompactTextString(m) }
func (*CportInfo) ProtoMessage()    {}
func (*CportInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{13}
}

func (m *CportInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CportInfo.Unmarshal(m, b)
}
func (m *CportInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CportInfo.Marshal(b, m, deterministic)
}
func (m *CportInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CportInfo.Merge(m, src)
}
func (m *CportInfo) XXX_Size() int {
	return xxx_messageInfo_CportInfo.Size(m)
}
func (m *CportInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CportInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CportInfo proto.InternalMessageInfo

func (m *CportInfo) GetCportUuid() string {
	if m != nil {
		return m.CportUuid
	}
	return ""
}

func (m *CportInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CportInfo) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *CportInfo) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *CportInfo) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *CportInfo) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *CportInfo) GetPodNs() string {
	if m != nil {
		return m.PodNs
	}
	return ""
}

func (m *CportInfo) GetVmNicUuid() string {
	if m != nil {
		return m.VmNicUuid
	}
	return ""
}

func (m *CportInfo) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *CportInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *CportInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *CportInfo) GetJob() *v1.JobInfo {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobResultRequest struct {
	Header               *v1.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	JobUuids             []string   `protobuf:"bytes,2,rep,name=jobUuids,proto3" json:"jobUuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JobResultRequest) Reset()         { *m = JobResultRequest{} }
func (m *JobResultRequest) String() string { return proto.CompactTextString(m) }
func (*JobResultRequest) ProtoMessage()    {}
func (*JobResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{14}
}

func (m *JobResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResultRequest.Unmarshal(m, b)
}
func (m *JobResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResultRequest.Marshal(b, m, deterministic)
}
func (m *JobResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResultRequest.Merge(m, src)
}
func (m *JobResultRequest) XXX_Size() int {
	return xxx_messageInfo_JobResultRequest.Size(m)
}
func (m *JobResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobResultRequest proto.InternalMessageInfo

func (m *JobResultRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *JobResultRequest) GetJobUuids() []string {
	if m != nil {
		return m.JobUuids
	}
	return nil
}

type JobResultResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JobResultResponse) Reset()         { *m = JobResultResponse{} }
func (m *JobResultResponse) String() string { return proto.CompactTextString(m) }
func (*JobResultResponse) ProtoMessage()    {}
func (*JobResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{15}
}

func (m *JobResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResultResponse.Unmarshal(m, b)
}
func (m *JobResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResultResponse.Marshal(b, m, deterministic)
}
func (m *JobResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResultResponse.Merge(m, src)
}
func (m *JobResultResponse) XXX_Size() int {
	return xxx_messageInfo_JobResultResponse.Size(m)
}
func (m *JobResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResultResponse proto.InternalMessageInfo

func (m *JobResultResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *JobResultResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListRegionAndZoneRequest struct {
	Header               *v1.Header                          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Condition            *ListRegionAndZoneRequest_Condition `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ListRegionAndZoneRequest) Reset()         { *m = ListRegionAndZoneRequest{} }
func (m *ListRegionAndZoneRequest) String() string { return proto.CompactTextString(m) }
func (*ListRegionAndZoneRequest) ProtoMessage()    {}
func (*ListRegionAndZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{16}
}

func (m *ListRegionAndZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRegionAndZoneRequest.Unmarshal(m, b)
}
func (m *ListRegionAndZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRegionAndZoneRequest.Marshal(b, m, deterministic)
}
func (m *ListRegionAndZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRegionAndZoneRequest.Merge(m, src)
}
func (m *ListRegionAndZoneRequest) XXX_Size() int {
	return xxx_messageInfo_ListRegionAndZoneRequest.Size(m)
}
func (m *ListRegionAndZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRegionAndZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRegionAndZoneRequest proto.InternalMessageInfo

func (m *ListRegionAndZoneRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ListRegionAndZoneRequest) GetCondition() *ListRegionAndZoneRequest_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type ListRegionAndZoneRequest_Condition struct {
	Product              string   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRegionAndZoneRequest_Condition) Reset()         { *m = ListRegionAndZoneRequest_Condition{} }
func (m *ListRegionAndZoneRequest_Condition) String() string { return proto.CompactTextString(m) }
func (*ListRegionAndZoneRequest_Condition) ProtoMessage()    {}
func (*ListRegionAndZoneRequest_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{16, 0}
}

func (m *ListRegionAndZoneRequest_Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRegionAndZoneRequest_Condition.Unmarshal(m, b)
}
func (m *ListRegionAndZoneRequest_Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRegionAndZoneRequest_Condition.Marshal(b, m, deterministic)
}
func (m *ListRegionAndZoneRequest_Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRegionAndZoneRequest_Condition.Merge(m, src)
}
func (m *ListRegionAndZoneRequest_Condition) XXX_Size() int {
	return xxx_messageInfo_ListRegionAndZoneRequest_Condition.Size(m)
}
func (m *ListRegionAndZoneRequest_Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRegionAndZoneRequest_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_ListRegionAndZoneRequest_Condition proto.InternalMessageInfo

func (m *ListRegionAndZoneRequest_Condition) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

type RegionData struct {
	AreaName             string         `protobuf:"bytes,1,opt,name=areaName,proto3" json:"areaName,omitempty"`
	Id                   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Zone                 []*v1.ZoneInfo `protobuf:"bytes,4,rep,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RegionData) Reset()         { *m = RegionData{} }
func (m *RegionData) String() string { return proto.CompactTextString(m) }
func (*RegionData) ProtoMessage()    {}
func (*RegionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{17}
}

func (m *RegionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionData.Unmarshal(m, b)
}
func (m *RegionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionData.Marshal(b, m, deterministic)
}
func (m *RegionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionData.Merge(m, src)
}
func (m *RegionData) XXX_Size() int {
	return xxx_messageInfo_RegionData.Size(m)
}
func (m *RegionData) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionData.DiscardUnknown(m)
}

var xxx_messageInfo_RegionData proto.InternalMessageInfo

func (m *RegionData) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

func (m *RegionData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegionData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegionData) GetZone() []*v1.ZoneInfo {
	if m != nil {
		return m.Zone
	}
	return nil
}

type ListRegionAndZoneResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*RegionData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListRegionAndZoneResponse) Reset()         { *m = ListRegionAndZoneResponse{} }
func (m *ListRegionAndZoneResponse) String() string { return proto.CompactTextString(m) }
func (*ListRegionAndZoneResponse) ProtoMessage()    {}
func (*ListRegionAndZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33ad1656df73a163, []int{18}
}

func (m *ListRegionAndZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRegionAndZoneResponse.Unmarshal(m, b)
}
func (m *ListRegionAndZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRegionAndZoneResponse.Marshal(b, m, deterministic)
}
func (m *ListRegionAndZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRegionAndZoneResponse.Merge(m, src)
}
func (m *ListRegionAndZoneResponse) XXX_Size() int {
	return xxx_messageInfo_ListRegionAndZoneResponse.Size(m)
}
func (m *ListRegionAndZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRegionAndZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRegionAndZoneResponse proto.InternalMessageInfo

func (m *ListRegionAndZoneResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListRegionAndZoneResponse) GetData() []*RegionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Dc2Info)(nil), "didi.cloud.compute.v1.Dc2Info")
	proto.RegisterType((*EipInfo)(nil), "didi.cloud.compute.v1.EipInfo")
	proto.RegisterType((*EbsInfo)(nil), "didi.cloud.compute.v1.EbsInfo")
	proto.RegisterType((*SlbInfo)(nil), "didi.cloud.compute.v1.SlbInfo")
	proto.RegisterType((*BeipInfo)(nil), "didi.cloud.compute.v1.BeipInfo")
	proto.RegisterType((*FlowInfo)(nil), "didi.cloud.compute.v1.FlowInfo")
	proto.RegisterType((*SpecInfo)(nil), "didi.cloud.compute.v1.SpecInfo")
	proto.RegisterType((*SnapInfo)(nil), "didi.cloud.compute.v1.SnapInfo")
	proto.RegisterType((*VpcInfo)(nil), "didi.cloud.compute.v1.VpcInfo")
	proto.RegisterType((*SubnetInfo)(nil), "didi.cloud.compute.v1.SubnetInfo")
	proto.RegisterType((*TotalCntInfo)(nil), "didi.cloud.compute.v1.TotalCntInfo")
	proto.RegisterType((*SgInfo)(nil), "didi.cloud.compute.v1.SgInfo")
	proto.RegisterType((*SgRuleInfo)(nil), "didi.cloud.compute.v1.SgRuleInfo")
	proto.RegisterType((*CportInfo)(nil), "didi.cloud.compute.v1.CportInfo")
	proto.RegisterType((*JobResultRequest)(nil), "didi.cloud.compute.v1.JobResultRequest")
	proto.RegisterType((*JobResultResponse)(nil), "didi.cloud.compute.v1.JobResultResponse")
	proto.RegisterType((*ListRegionAndZoneRequest)(nil), "didi.cloud.compute.v1.ListRegionAndZoneRequest")
	proto.RegisterType((*ListRegionAndZoneRequest_Condition)(nil), "didi.cloud.compute.v1.ListRegionAndZoneRequest.Condition")
	proto.RegisterType((*RegionData)(nil), "didi.cloud.compute.v1.RegionData")
	proto.RegisterType((*ListRegionAndZoneResponse)(nil), "didi.cloud.compute.v1.ListRegionAndZoneResponse")
}

func init() {
	proto.RegisterFile("compute/v1/common.proto", fileDescriptor_33ad1656df73a163)
}

var fileDescriptor_33ad1656df73a163 = []byte{
	// 1558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x8f, 0x1b, 0xc5,
	0x16, 0x96, 0xbb, 0x3d, 0x7e, 0x1c, 0x27, 0xb9, 0x49, 0xeb, 0x26, 0xe9, 0xcc, 0x9d, 0xe4, 0xce,
	0x6d, 0xdd, 0x88, 0x11, 0x62, 0xec, 0x19, 0x07, 0x90, 0x50, 0xc4, 0x82, 0xcc, 0x04, 0x48, 0x84,
	0xa2, 0xa8, 0x3d, 0x04, 0x29, 0xca, 0xa6, 0xba, 0xbb, 0xec, 0x54, 0xd2, 0xee, 0x6a, 0xba, 0xab,
	0x3d, 0x24, 0x0b, 0x16, 0xb0, 0x60, 0x85, 0x84, 0x84, 0xd8, 0xb0, 0x66, 0xc5, 0x8e, 0x3f, 0xc0,
	0x0f, 0x60, 0xc1, 0x86, 0x3d, 0x12, 0x52, 0x16, 0xfc, 0x04, 0x76, 0xa0, 0x3a, 0x55, 0xfd, 0xb0,
	0xc7, 0x8e, 0x3d, 0x13, 0x45, 0xb0, 0x72, 0x7d, 0xa7, 0x4e, 0x3d, 0xce, 0x77, 0x5e, 0xd5, 0x86,
	0x8b, 0x3e, 0x1f, 0xc7, 0x99, 0xa0, 0xbd, 0xc9, 0x6e, 0xcf, 0xe7, 0xe3, 0x31, 0x8f, 0xba, 0x71,
	0xc2, 0x05, 0xb7, 0xce, 0x07, 0x2c, 0x60, 0x5d, 0x3f, 0xe4, 0x59, 0xd0, 0xd5, 0x3a, 0xdd, 0xc9,
	0xee, 0xba, 0xe5, 0x91, 0x14, 0x95, 0xe5, 0xaf, 0x52, 0x5d, 0xb7, 0x3c, 0x16, 0x86, 0x28, 0x63,
	0x61, 0xa8, 0x65, 0x1b, 0x23, 0xce, 0x47, 0x21, 0xed, 0x91, 0x98, 0xf5, 0x48, 0x14, 0x71, 0x41,
	0x04, 0xe3, 0x51, 0xaa, 0x66, 0x9d, 0xdf, 0x4d, 0x68, 0xee, 0xfb, 0xfd, 0x5b, 0xd1, 0x90, 0x5b,
	0x36, 0x34, 0x03, 0xbf, 0xff, 0x61, 0xc6, 0x02, 0xbb, 0xb6, 0x59, 0xdb, 0x6a, 0xbb, 0x39, 0xb4,
	0x2c, 0xa8, 0x47, 0x64, 0x4c, 0x6d, 0x03, 0xc5, 0x38, 0xb6, 0xae, 0x00, 0xf8, 0x09, 0x25, 0x82,
	0x1e, 0xb0, 0x31, 0xb5, 0xcd, 0xcd, 0xda, 0x96, 0xe9, 0x56, 0x24, 0x72, 0x3e, 0x8b, 0x83, 0x7c,
	0xbe, 0xae, 0xe6, 0x4b, 0x89, 0x75, 0x06, 0x0c, 0x16, 0xdb, 0x6b, 0xb8, 0xa3, 0xc1, 0x62, 0xeb,
	0x02, 0x34, 0x52, 0x41, 0x44, 0x96, 0xda, 0x0d, 0x94, 0x69, 0x24, 0xe5, 0x3c, 0x3d, 0x78, 0x12,
	0x53, 0xbb, 0xa9, 0xe4, 0x0a, 0x59, 0xeb, 0xd0, 0x8a, 0x43, 0x22, 0x86, 0x3c, 0x19, 0xdb, 0x2d,
	0x9c, 0x29, 0xb0, 0xb4, 0x84, 0x8d, 0x47, 0x68, 0x49, 0x5b, 0x59, 0xa2, 0xa1, 0xf5, 0x6f, 0x58,
	0x63, 0xe3, 0xd1, 0xad, 0xc0, 0x06, 0x94, 0x2b, 0xa0, 0x2d, 0x3f, 0x20, 0xa3, 0xd4, 0xee, 0x6c,
	0x9a, 0xda, 0x72, 0x09, 0xad, 0x6d, 0x30, 0x1f, 0x71, 0xcf, 0x3e, 0xb5, 0x59, 0xdb, 0xea, 0xf4,
	0xff, 0xd3, 0xad, 0xb8, 0x02, 0x69, 0x9f, 0xec, 0x76, 0x6f, 0x73, 0x4f, 0xb2, 0xe7, 0x4a, 0x3d,
	0x6b, 0x07, 0x4c, 0xca, 0x62, 0xfb, 0x34, 0xaa, 0x5f, 0xe9, 0xce, 0xf5, 0x5c, 0xf7, 0x26, 0x8b,
	0xd5, 0x0a, 0xca, 0x62, 0x5c, 0xe1, 0xa5, 0xf6, 0x99, 0x4d, 0xf3, 0x79, 0x2b, 0xbc, 0x54, 0xaf,
	0xf0, 0x52, 0xeb, 0x4d, 0x68, 0x24, 0x74, 0xc4, 0x78, 0x64, 0xff, 0xeb, 0xe8, 0x31, 0xf9, 0xad,
	0x5c, 0xd4, 0xc0, 0x45, 0x5a, 0xdb, 0xf9, 0xd1, 0x80, 0xa6, 0x3e, 0x5a, 0x93, 0x5f, 0x2b, 0xc8,
	0xb7, 0xa1, 0x49, 0x59, 0x8c, 0x84, 0x29, 0x1f, 0xe7, 0x50, 0xcf, 0x20, 0x35, 0xa6, 0xa2, 0x46,
	0xc3, 0x8a, 0xc3, 0xea, 0x53, 0x0e, 0x2b, 0xef, 0xb7, 0x76, 0x9c, 0xfb, 0xcd, 0x04, 0x54, 0x63,
	0x49, 0x40, 0x35, 0x8f, 0x04, 0xd4, 0x0e, 0x98, 0x81, 0xdf, 0xc7, 0x58, 0x58, 0xcc, 0xa4, 0x8e,
	0x75, 0x57, 0xaa, 0xe6, 0xce, 0x6d, 0xaf, 0xe6, 0x5c, 0xe7, 0x4b, 0x13, 0x9a, 0xda, 0x13, 0x45,
	0x46, 0xd4, 0x2a, 0x19, 0x21, 0xa9, 0xf2, 0xd2, 0x29, 0x12, 0x15, 0x94, 0xda, 0x42, 0x46, 0xb0,
	0xa9, 0xb4, 0xe5, 0x58, 0xca, 0x88, 0x10, 0x89, 0x26, 0x0f, 0xc7, 0x7a, 0x07, 0x24, 0x7b, 0x4d,
	0x93, 0xad, 0xa0, 0xf5, 0x76, 0x41, 0x6a, 0x03, 0x6f, 0x7b, 0x75, 0x31, 0xa9, 0xef, 0x44, 0xc1,
	0x7d, 0x1e, 0xd1, 0x59, 0x6e, 0x03, 0x3a, 0x61, 0x3e, 0xbd, 0x43, 0xc6, 0x79, 0x22, 0x55, 0x24,
	0x33, 0xdc, 0xb7, 0x96, 0x70, 0xdf, 0x3e, 0xc2, 0xbd, 0x66, 0x12, 0x56, 0x4f, 0x13, 0xe9, 0xaa,
	0xce, 0xea, 0xae, 0xb2, 0xa0, 0x9e, 0xb2, 0xa7, 0x14, 0x13, 0xd1, 0x74, 0x71, 0xec, 0xfc, 0x69,
	0x42, 0x73, 0x10, 0x7a, 0x79, 0xed, 0x4a, 0x43, 0xaf, 0x5a, 0xbb, 0x34, 0x9c, 0x5b, 0xbb, 0x54,
	0xf8, 0x9b, 0x45, 0xf8, 0x6f, 0x40, 0xfb, 0x90, 0x0c, 0x07, 0xd5, 0x68, 0x2e, 0x05, 0x33, 0xe4,
	0xac, 0x2d, 0x21, 0xa7, 0x71, 0x84, 0x9c, 0x6b, 0x50, 0xf7, 0x64, 0x55, 0x68, 0xa2, 0xb9, 0xff,
	0x5d, 0x60, 0xee, 0x0d, 0xaa, 0xcb, 0x02, 0x2a, 0x4b, 0x8a, 0x26, 0xb1, 0xbf, 0x24, 0x9a, 0xef,
	0xc5, 0xbe, 0xa2, 0x68, 0x12, 0xfb, 0xf2, 0x98, 0x61, 0xc8, 0x0f, 0x75, 0x38, 0x2f, 0x3a, 0xe6,
	0xdd, 0x90, 0x1f, 0xaa, 0x63, 0xa4, 0xb2, 0x75, 0x1d, 0x5a, 0x03, 0xaa, 0x76, 0xd1, 0xde, 0x5b,
	0xb4, 0x70, 0x10, 0x53, 0x75, 0x58, 0xb1, 0xa0, 0x92, 0xe9, 0x9d, 0x63, 0x65, 0xfa, 0x31, 0x8b,
	0xaa, 0xf2, 0x2d, 0x66, 0xc5, 0x69, 0x95, 0x15, 0x1a, 0x3a, 0x13, 0x68, 0xe5, 0xb4, 0xc9, 0x7e,
	0xe0, 0xe5, 0x35, 0x4c, 0x85, 0x40, 0x81, 0xb5, 0xbf, 0x8d, 0xc2, 0xdf, 0x2f, 0xd8, 0xbb, 0x9c,
	0xd7, 0xa0, 0x95, 0xf3, 0x88, 0x7b, 0x47, 0x78, 0xa2, 0xe1, 0x1a, 0x2c, 0xb2, 0xce, 0x82, 0xc9,
	0x33, 0x81, 0x87, 0x19, 0xae, 0x1c, 0x3a, 0x5d, 0x68, 0xe5, 0xe4, 0x59, 0x0e, 0x9c, 0xe2, 0xc3,
	0x21, 0x4d, 0x58, 0x34, 0xaa, 0xdc, 0x74, 0x4a, 0xe6, 0xfc, 0x60, 0x42, 0x6b, 0x10, 0x91, 0xc2,
	0xac, 0x34, 0x22, 0x53, 0x66, 0xe5, 0x78, 0x6e, 0x68, 0xff, 0x1f, 0x4e, 0xfb, 0x24, 0xba, 0x41,
	0x5d, 0x3a, 0xa1, 0x89, 0xa0, 0x01, 0x5a, 0xd7, 0x72, 0xa7, 0x85, 0x32, 0xe0, 0x59, 0xfa, 0x1e,
	0x8d, 0x68, 0x42, 0x42, 0xb4, 0xaf, 0xe5, 0x96, 0x82, 0x17, 0x0e, 0xf8, 0x3c, 0x59, 0x9b, 0x65,
	0xb2, 0x16, 0x25, 0xb0, 0x55, 0x29, 0x81, 0xba, 0x0c, 0xb4, 0x57, 0x2f, 0x03, 0xba, 0x5b, 0xc2,
	0xf3, 0xfb, 0xeb, 0xfc, 0x6e, 0xf9, 0x32, 0x63, 0xd4, 0xf9, 0xca, 0x80, 0xa6, 0xce, 0x46, 0x19,
	0xaf, 0x93, 0xd8, 0xaf, 0xd6, 0x22, 0x0d, 0x5f, 0xca, 0x3b, 0x0a, 0x5d, 0xb9, 0x4f, 0x87, 0x24,
	0x0b, 0x05, 0xfa, 0x0a, 0x5d, 0xa9, 0x05, 0xf2, 0x44, 0x9f, 0x05, 0x89, 0x7e, 0x53, 0xe1, 0xb8,
	0x42, 0x49, 0xf3, 0x24, 0x94, 0xb4, 0x56, 0xa4, 0xe4, 0x59, 0x0d, 0x60, 0x90, 0x79, 0x11, 0x15,
	0xc8, 0xca, 0x15, 0x80, 0x14, 0x51, 0x85, 0x98, 0x8a, 0xe4, 0x1f, 0xc2, 0xcd, 0x0e, 0xd4, 0x9f,
	0xf2, 0x88, 0x6a, 0x66, 0x36, 0xe6, 0x19, 0x59, 0x34, 0x57, 0xd4, 0x74, 0x5e, 0x85, 0x53, 0x07,
	0x5c, 0x90, 0x70, 0x2f, 0x12, 0x79, 0xc2, 0x0a, 0x8d, 0xd1, 0xca, 0x35, 0xb7, 0xc0, 0xce, 0x6f,
	0x06, 0x34, 0x06, 0x23, 0x54, 0x93, 0xaf, 0xa7, 0x6a, 0x09, 0xd0, 0xe8, 0x6f, 0xa0, 0xe1, 0x02,
	0x34, 0x02, 0xbf, 0x2f, 0xaf, 0xab, 0x32, 0x59, 0x23, 0xb9, 0x2a, 0x1d, 0xb9, 0x59, 0x48, 0xe5,
	0x94, 0x4a, 0xe5, 0x52, 0x70, 0x82, 0xfe, 0x54, 0x86, 0x5d, 0xfb, 0x24, 0x61, 0xb7, 0xe2, 0xdb,
	0xc2, 0xf9, 0xce, 0x04, 0x18, 0xe0, 0x35, 0x8b, 0xb0, 0x43, 0x34, 0x15, 0x76, 0x85, 0x64, 0x86,
	0x5b, 0x63, 0x09, 0xb7, 0xe6, 0xbc, 0x5a, 0x87, 0x75, 0xad, 0x5e, 0xa9, 0x6b, 0xf2, 0xd3, 0x44,
	0x7e, 0x5d, 0xf9, 0x3c, 0xd4, 0x1f, 0x38, 0x05, 0x46, 0x56, 0x05, 0x49, 0xc4, 0x5d, 0x9e, 0xe4,
	0x84, 0x97, 0x02, 0x7c, 0x00, 0x46, 0x01, 0xce, 0x29, 0xc6, 0x73, 0x68, 0x6d, 0x42, 0x87, 0x84,
	0x21, 0x3f, 0xa4, 0xc1, 0x9e, 0x8c, 0x59, 0x55, 0x46, 0xab, 0xa2, 0x69, 0x2f, 0xb7, 0x67, 0xbd,
	0xbc, 0x0d, 0x46, 0x3a, 0xd2, 0x24, 0x5e, 0x5e, 0xd4, 0xe2, 0x31, 0x34, 0x5d, 0x23, 0x1d, 0xe5,
	0xee, 0xed, 0xac, 0xee, 0xde, 0x63, 0x16, 0xcc, 0x5f, 0x0d, 0x68, 0xef, 0xc5, 0x3c, 0x51, 0x49,
	0xb3, 0x01, 0x6d, 0x5f, 0x82, 0x8a, 0x93, 0x4a, 0xc1, 0x91, 0xf6, 0xbd, 0x09, 0x1d, 0x9f, 0x47,
	0x82, 0xb0, 0x88, 0x26, 0xb7, 0x02, 0xfd, 0x8e, 0xab, 0x8a, 0x64, 0x13, 0x1e, 0x13, 0x5f, 0x3b,
	0x45, 0x0e, 0x25, 0xb3, 0x11, 0x15, 0x63, 0x92, 0x3e, 0xd6, 0x2e, 0xc9, 0xa1, 0x9c, 0x89, 0x79,
	0x80, 0x0f, 0x63, 0x55, 0x09, 0x72, 0x28, 0x3f, 0x16, 0xe5, 0x30, 0xd5, 0x0f, 0x66, 0x05, 0xe4,
	0x5d, 0x27, 0xe3, 0x3b, 0x4c, 0x15, 0x78, 0xe5, 0x87, 0x52, 0x20, 0x77, 0x1b, 0x11, 0x41, 0x0f,
	0xc9, 0x93, 0xfc, 0xd3, 0x53, 0xc3, 0x99, 0x48, 0x83, 0x25, 0x91, 0xd6, 0x59, 0xf4, 0xc6, 0x5e,
	0x95, 0x60, 0x0f, 0xce, 0xde, 0xe6, 0x9e, 0x4b, 0xd3, 0x2c, 0x14, 0x2e, 0xfd, 0x38, 0xa3, 0xa9,
	0xb0, 0xfa, 0xd0, 0x78, 0x48, 0x49, 0x40, 0x13, 0xe4, 0xb8, 0xd3, 0x5f, 0x9f, 0xb7, 0xcb, 0xfb,
	0xa8, 0xe1, 0x6a, 0x4d, 0x19, 0xcc, 0x8f, 0x38, 0x3e, 0xa5, 0x53, 0xdb, 0xc0, 0xe7, 0x57, 0x81,
	0x9d, 0x0c, 0xce, 0x55, 0xce, 0x48, 0x63, 0x1e, 0xa5, 0xd4, 0xea, 0xc1, 0x1a, 0x4d, 0x12, 0x9e,
	0x9f, 0x71, 0x69, 0xde, 0x19, 0x37, 0xa5, 0x82, 0xab, 0xf4, 0xac, 0x1e, 0xd4, 0x03, 0x22, 0x08,
	0xee, 0xbe, 0xc4, 0x32, 0x54, 0x74, 0x7e, 0xae, 0x81, 0xfd, 0x01, 0x4b, 0xc5, 0xd4, 0xf7, 0xce,
	0x8b, 0xd8, 0xf8, 0x11, 0xb4, 0x7d, 0x1e, 0x05, 0x4c, 0xc8, 0xea, 0x64, 0xe0, 0xb2, 0xb7, 0x16,
	0xc4, 0xfc, 0xa2, 0x73, 0xbb, 0x7b, 0xf9, 0x06, 0x6e, 0xb9, 0xd7, 0xfa, 0x55, 0x68, 0x17, 0x72,
	0x0c, 0xb4, 0x84, 0x07, 0x99, 0x2f, 0xf2, 0x77, 0x81, 0x86, 0xce, 0xa7, 0x00, 0x6a, 0xcf, 0x7d,
	0x22, 0x88, 0x64, 0x9c, 0x24, 0x94, 0xdc, 0x29, 0xbf, 0x2f, 0x0b, 0x8c, 0xa9, 0x10, 0x14, 0xa9,
	0x50, 0xb6, 0x0b, 0xb3, 0xd2, 0x2e, 0xf2, 0x1e, 0x56, 0x47, 0x3e, 0x57, 0xe9, 0x61, 0x9f, 0xd7,
	0xe0, 0xd2, 0x1c, 0xc3, 0x4e, 0xea, 0xd0, 0x37, 0xa6, 0x1c, 0xfa, 0xbf, 0x05, 0x4c, 0x96, 0x16,
	0x2b, 0xb7, 0xf6, 0xbf, 0x35, 0xa0, 0xb1, 0x87, 0xff, 0x7c, 0x59, 0x9f, 0x40, 0xbb, 0x08, 0x2c,
	0xeb, 0x95, 0x05, 0x1b, 0xcc, 0x86, 0xf7, 0xfa, 0xd6, 0x72, 0x45, 0x65, 0x92, 0x63, 0x7f, 0xf6,
	0xcb, 0xb3, 0xaf, 0x0d, 0xcb, 0x3a, 0x1b, 0x30, 0xd4, 0xee, 0xb1, 0x5e, 0xa2, 0x0e, 0xfb, 0xa6,
	0x06, 0xe7, 0x8e, 0x50, 0x61, 0xf5, 0x8e, 0x19, 0x0d, 0xeb, 0x3b, 0xab, 0x2f, 0xd0, 0x57, 0xba,
	0x8c, 0x57, 0xba, 0xe8, 0x9c, 0xaf, 0x5e, 0x49, 0x2a, 0xf6, 0x42, 0x96, 0x8a, 0x1b, 0x5f, 0xd4,
	0xe0, 0x82, 0xcf, 0xc7, 0xb8, 0xed, 0x93, 0x2c, 0xaa, 0xec, 0x79, 0xb7, 0x76, 0xff, 0xf5, 0x11,
	0x13, 0x0f, 0x33, 0x4f, 0x0a, 0x7b, 0x5a, 0x21, 0xff, 0xdd, 0x1e, 0xf1, 0xed, 0x34, 0x78, 0xdc,
	0x2b, 0xff, 0x5d, 0xbc, 0xae, 0x87, 0x7f, 0xd4, 0x6a, 0xdf, 0x1b, 0x17, 0xf7, 0xe5, 0x35, 0xf7,
	0xd5, 0x91, 0xdd, 0x3d, 0xbd, 0xe9, 0xbd, 0xdd, 0x9f, 0xd4, 0xcc, 0x03, 0x3d, 0xf3, 0x40, 0xcf,
	0x3c, 0xb8, 0xb7, 0xeb, 0x35, 0xb0, 0x97, 0x5d, 0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x52,
	0x08, 0x6b, 0xb1, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommonClient is the client API for Common service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonClient interface {
	// 获取任务进度
	JobResult(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResultResponse, error)
	// 获取产品可用区列表
	ListRegionAndZone(ctx context.Context, in *ListRegionAndZoneRequest, opts ...grpc.CallOption) (*ListRegionAndZoneResponse, error)
}

type commonClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonClient(cc grpc.ClientConnInterface) CommonClient {
	return &commonClient{cc}
}

func (c *commonClient) JobResult(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResultResponse, error) {
	out := new(JobResultResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Common/JobResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commonClient) ListRegionAndZone(ctx context.Context, in *ListRegionAndZoneRequest, opts ...grpc.CallOption) (*ListRegionAndZoneResponse, error) {
	out := new(ListRegionAndZoneResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Common/ListRegionAndZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServer is the server API for Common service.
type CommonServer interface {
	// 获取任务进度
	JobResult(context.Context, *JobResultRequest) (*JobResultResponse, error)
	// 获取产品可用区列表
	ListRegionAndZone(context.Context, *ListRegionAndZoneRequest) (*ListRegionAndZoneResponse, error)
}

// UnimplementedCommonServer can be embedded to have forward compatible implementations.
type UnimplementedCommonServer struct {
}

func (*UnimplementedCommonServer) JobResult(ctx context.Context, req *JobResultRequest) (*JobResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobResult not implemented")
}
func (*UnimplementedCommonServer) ListRegionAndZone(ctx context.Context, req *ListRegionAndZoneRequest) (*ListRegionAndZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRegionAndZone not implemented")
}

func RegisterCommonServer(s *grpc.Server, srv CommonServer) {
	s.RegisterService(&_Common_serviceDesc, srv)
}

func _Common_JobResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).JobResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Common/JobResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).JobResult(ctx, req.(*JobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Common_ListRegionAndZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegionAndZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).ListRegionAndZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Common/ListRegionAndZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).ListRegionAndZone(ctx, req.(*ListRegionAndZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Common_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didi.cloud.compute.v1.Common",
	HandlerType: (*CommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobResult",
			Handler:    _Common_JobResult_Handler,
		},
		{
			MethodName: "ListRegionAndZone",
			Handler:    _Common_ListRegionAndZone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute/v1/common.proto",
}
