// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compute/v1/eip.proto

// eip Service
//
// eip Service API consists of a single service which returns
// a message.

package compute

import (
	context "context"
	fmt "fmt"
	v1 "github.com/didiyun/didiyun-go-sdk/base/v1"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CommonResponse represents a common response return from dicloud service.
type ListEipResponse struct {
	Error                *v1.Error  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*EipInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListEipResponse) Reset()         { *m = ListEipResponse{} }
func (m *ListEipResponse) String() string { return proto.CompactTextString(m) }
func (*ListEipResponse) ProtoMessage()    {}
func (*ListEipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{0}
}

func (m *ListEipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEipResponse.Unmarshal(m, b)
}
func (m *ListEipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEipResponse.Marshal(b, m, deterministic)
}
func (m *ListEipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEipResponse.Merge(m, src)
}
func (m *ListEipResponse) XXX_Size() int {
	return xxx_messageInfo_ListEipResponse.Size(m)
}
func (m *ListEipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEipResponse proto.InternalMessageInfo

func (m *ListEipResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListEipResponse) GetData() []*EipInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListEipCondition struct {
	Eip                  string   `protobuf:"bytes,1,opt,name=eip,proto3" json:"eip,omitempty"`
	EipUuids             []string `protobuf:"bytes,2,rep,name=eipUuids,proto3" json:"eipUuids,omitempty"`
	EipNotAttached       bool     `protobuf:"varint,3,opt,name=eipNotAttached,proto3" json:"eipNotAttached,omitempty"`
	Dc2Uuid              string   `protobuf:"bytes,4,opt,name=dc2Uuid,proto3" json:"dc2Uuid,omitempty"`
	Dc2Name              string   `protobuf:"bytes,5,opt,name=dc2Name,proto3" json:"dc2Name,omitempty"`
	Bandwidth            int32    `protobuf:"varint,6,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEipCondition) Reset()         { *m = ListEipCondition{} }
func (m *ListEipCondition) String() string { return proto.CompactTextString(m) }
func (*ListEipCondition) ProtoMessage()    {}
func (*ListEipCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{1}
}

func (m *ListEipCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEipCondition.Unmarshal(m, b)
}
func (m *ListEipCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEipCondition.Marshal(b, m, deterministic)
}
func (m *ListEipCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEipCondition.Merge(m, src)
}
func (m *ListEipCondition) XXX_Size() int {
	return xxx_messageInfo_ListEipCondition.Size(m)
}
func (m *ListEipCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEipCondition.DiscardUnknown(m)
}

var xxx_messageInfo_ListEipCondition proto.InternalMessageInfo

func (m *ListEipCondition) GetEip() string {
	if m != nil {
		return m.Eip
	}
	return ""
}

func (m *ListEipCondition) GetEipUuids() []string {
	if m != nil {
		return m.EipUuids
	}
	return nil
}

func (m *ListEipCondition) GetEipNotAttached() bool {
	if m != nil {
		return m.EipNotAttached
	}
	return false
}

func (m *ListEipCondition) GetDc2Uuid() string {
	if m != nil {
		return m.Dc2Uuid
	}
	return ""
}

func (m *ListEipCondition) GetDc2Name() string {
	if m != nil {
		return m.Dc2Name
	}
	return ""
}

func (m *ListEipCondition) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

type ListEipRequest struct {
	Header               *v1.Header        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Start                int32             `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Limit                int32             `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Simplify             bool              `protobuf:"varint,4,opt,name=simplify,proto3" json:"simplify,omitempty"`
	Condition            *ListEipCondition `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListEipRequest) Reset()         { *m = ListEipRequest{} }
func (m *ListEipRequest) String() string { return proto.CompactTextString(m) }
func (*ListEipRequest) ProtoMessage()    {}
func (*ListEipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{2}
}

func (m *ListEipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEipRequest.Unmarshal(m, b)
}
func (m *ListEipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEipRequest.Marshal(b, m, deterministic)
}
func (m *ListEipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEipRequest.Merge(m, src)
}
func (m *ListEipRequest) XXX_Size() int {
	return xxx_messageInfo_ListEipRequest.Size(m)
}
func (m *ListEipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEipRequest proto.InternalMessageInfo

func (m *ListEipRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ListEipRequest) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListEipRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListEipRequest) GetSimplify() bool {
	if m != nil {
		return m.Simplify
	}
	return false
}

func (m *ListEipRequest) GetCondition() *ListEipCondition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type GetEipTotalCntRequest struct {
	Header               *v1.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Eip                  string     `protobuf:"bytes,2,opt,name=eip,proto3" json:"eip,omitempty"`
	EipUuids             []string   `protobuf:"bytes,3,rep,name=eipUuids,proto3" json:"eipUuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetEipTotalCntRequest) Reset()         { *m = GetEipTotalCntRequest{} }
func (m *GetEipTotalCntRequest) String() string { return proto.CompactTextString(m) }
func (*GetEipTotalCntRequest) ProtoMessage()    {}
func (*GetEipTotalCntRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{3}
}

func (m *GetEipTotalCntRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEipTotalCntRequest.Unmarshal(m, b)
}
func (m *GetEipTotalCntRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEipTotalCntRequest.Marshal(b, m, deterministic)
}
func (m *GetEipTotalCntRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEipTotalCntRequest.Merge(m, src)
}
func (m *GetEipTotalCntRequest) XXX_Size() int {
	return xxx_messageInfo_GetEipTotalCntRequest.Size(m)
}
func (m *GetEipTotalCntRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEipTotalCntRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEipTotalCntRequest proto.InternalMessageInfo

func (m *GetEipTotalCntRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetEipTotalCntRequest) GetEip() string {
	if m != nil {
		return m.Eip
	}
	return ""
}

func (m *GetEipTotalCntRequest) GetEipUuids() []string {
	if m != nil {
		return m.EipUuids
	}
	return nil
}

type GetEipTotalCntResponse struct {
	Error                *v1.Error       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*TotalCntInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetEipTotalCntResponse) Reset()         { *m = GetEipTotalCntResponse{} }
func (m *GetEipTotalCntResponse) String() string { return proto.CompactTextString(m) }
func (*GetEipTotalCntResponse) ProtoMessage()    {}
func (*GetEipTotalCntResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{4}
}

func (m *GetEipTotalCntResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEipTotalCntResponse.Unmarshal(m, b)
}
func (m *GetEipTotalCntResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEipTotalCntResponse.Marshal(b, m, deterministic)
}
func (m *GetEipTotalCntResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEipTotalCntResponse.Merge(m, src)
}
func (m *GetEipTotalCntResponse) XXX_Size() int {
	return xxx_messageInfo_GetEipTotalCntResponse.Size(m)
}
func (m *GetEipTotalCntResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEipTotalCntResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEipTotalCntResponse proto.InternalMessageInfo

func (m *GetEipTotalCntResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetEipTotalCntResponse) GetData() []*TotalCntInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetEipByUuidRequest struct {
	Header               *v1.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EipUuid              string     `protobuf:"bytes,2,opt,name=eipUuid,proto3" json:"eipUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetEipByUuidRequest) Reset()         { *m = GetEipByUuidRequest{} }
func (m *GetEipByUuidRequest) String() string { return proto.CompactTextString(m) }
func (*GetEipByUuidRequest) ProtoMessage()    {}
func (*GetEipByUuidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{5}
}

func (m *GetEipByUuidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEipByUuidRequest.Unmarshal(m, b)
}
func (m *GetEipByUuidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEipByUuidRequest.Marshal(b, m, deterministic)
}
func (m *GetEipByUuidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEipByUuidRequest.Merge(m, src)
}
func (m *GetEipByUuidRequest) XXX_Size() int {
	return xxx_messageInfo_GetEipByUuidRequest.Size(m)
}
func (m *GetEipByUuidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEipByUuidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEipByUuidRequest proto.InternalMessageInfo

func (m *GetEipByUuidRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetEipByUuidRequest) GetEipUuid() string {
	if m != nil {
		return m.EipUuid
	}
	return ""
}

type GetEipByUuidResponse struct {
	Error                *v1.Error  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*EipInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetEipByUuidResponse) Reset()         { *m = GetEipByUuidResponse{} }
func (m *GetEipByUuidResponse) String() string { return proto.CompactTextString(m) }
func (*GetEipByUuidResponse) ProtoMessage()    {}
func (*GetEipByUuidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{6}
}

func (m *GetEipByUuidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEipByUuidResponse.Unmarshal(m, b)
}
func (m *GetEipByUuidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEipByUuidResponse.Marshal(b, m, deterministic)
}
func (m *GetEipByUuidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEipByUuidResponse.Merge(m, src)
}
func (m *GetEipByUuidResponse) XXX_Size() int {
	return xxx_messageInfo_GetEipByUuidResponse.Size(m)
}
func (m *GetEipByUuidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEipByUuidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEipByUuidResponse proto.InternalMessageInfo

func (m *GetEipByUuidResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetEipByUuidResponse) GetData() []*EipInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateEipRequest struct {
	Header               *v1.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PayPeriod            int32      `protobuf:"varint,2,opt,name=payPeriod,proto3" json:"payPeriod,omitempty"`
	AutoContinue         bool       `protobuf:"varint,3,opt,name=autoContinue,proto3" json:"autoContinue,omitempty"`
	Count                int32      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	CouponId             string     `protobuf:"bytes,5,opt,name=couponId,proto3" json:"couponId,omitempty"`
	Tags                 []string   `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	ChargeWithFlow       bool       `protobuf:"varint,7,opt,name=chargeWithFlow,proto3" json:"chargeWithFlow,omitempty"`
	Bandwidth            int32      `protobuf:"varint,8,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	BindingUuid          string     `protobuf:"bytes,9,opt,name=bindingUuid,proto3" json:"bindingUuid,omitempty"`
	BindingType          string     `protobuf:"bytes,10,opt,name=bindingType,proto3" json:"bindingType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateEipRequest) Reset()         { *m = CreateEipRequest{} }
func (m *CreateEipRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEipRequest) ProtoMessage()    {}
func (*CreateEipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{7}
}

func (m *CreateEipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEipRequest.Unmarshal(m, b)
}
func (m *CreateEipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEipRequest.Marshal(b, m, deterministic)
}
func (m *CreateEipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEipRequest.Merge(m, src)
}
func (m *CreateEipRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEipRequest.Size(m)
}
func (m *CreateEipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEipRequest proto.InternalMessageInfo

func (m *CreateEipRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateEipRequest) GetPayPeriod() int32 {
	if m != nil {
		return m.PayPeriod
	}
	return 0
}

func (m *CreateEipRequest) GetAutoContinue() bool {
	if m != nil {
		return m.AutoContinue
	}
	return false
}

func (m *CreateEipRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CreateEipRequest) GetCouponId() string {
	if m != nil {
		return m.CouponId
	}
	return ""
}

func (m *CreateEipRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreateEipRequest) GetChargeWithFlow() bool {
	if m != nil {
		return m.ChargeWithFlow
	}
	return false
}

func (m *CreateEipRequest) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *CreateEipRequest) GetBindingUuid() string {
	if m != nil {
		return m.BindingUuid
	}
	return ""
}

func (m *CreateEipRequest) GetBindingType() string {
	if m != nil {
		return m.BindingType
	}
	return ""
}

type CreateEipResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateEipResponse) Reset()         { *m = CreateEipResponse{} }
func (m *CreateEipResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEipResponse) ProtoMessage()    {}
func (*CreateEipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{8}
}

func (m *CreateEipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEipResponse.Unmarshal(m, b)
}
func (m *CreateEipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEipResponse.Marshal(b, m, deterministic)
}
func (m *CreateEipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEipResponse.Merge(m, src)
}
func (m *CreateEipResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEipResponse.Size(m)
}
func (m *CreateEipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEipResponse proto.InternalMessageInfo

func (m *CreateEipResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreateEipResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ChangeEipBandwidthRequest struct {
	Header               *v1.Header                         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CouponId             string                             `protobuf:"bytes,2,opt,name=couponId,proto3" json:"couponId,omitempty"`
	Eip                  []*ChangeEipBandwidthRequest_Input `protobuf:"bytes,3,rep,name=eip,proto3" json:"eip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ChangeEipBandwidthRequest) Reset()         { *m = ChangeEipBandwidthRequest{} }
func (m *ChangeEipBandwidthRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEipBandwidthRequest) ProtoMessage()    {}
func (*ChangeEipBandwidthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{9}
}

func (m *ChangeEipBandwidthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEipBandwidthRequest.Unmarshal(m, b)
}
func (m *ChangeEipBandwidthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEipBandwidthRequest.Marshal(b, m, deterministic)
}
func (m *ChangeEipBandwidthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEipBandwidthRequest.Merge(m, src)
}
func (m *ChangeEipBandwidthRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEipBandwidthRequest.Size(m)
}
func (m *ChangeEipBandwidthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEipBandwidthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEipBandwidthRequest proto.InternalMessageInfo

func (m *ChangeEipBandwidthRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ChangeEipBandwidthRequest) GetCouponId() string {
	if m != nil {
		return m.CouponId
	}
	return ""
}

func (m *ChangeEipBandwidthRequest) GetEip() []*ChangeEipBandwidthRequest_Input {
	if m != nil {
		return m.Eip
	}
	return nil
}

type ChangeEipBandwidthRequest_Input struct {
	EipUuid              string   `protobuf:"bytes,1,opt,name=eipUuid,proto3" json:"eipUuid,omitempty"`
	Bandwidth            int32    `protobuf:"varint,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	ChargeWithFlow       bool     `protobuf:"varint,3,opt,name=chargeWithFlow,proto3" json:"chargeWithFlow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEipBandwidthRequest_Input) Reset()         { *m = ChangeEipBandwidthRequest_Input{} }
func (m *ChangeEipBandwidthRequest_Input) String() string { return proto.CompactTextString(m) }
func (*ChangeEipBandwidthRequest_Input) ProtoMessage()    {}
func (*ChangeEipBandwidthRequest_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{9, 0}
}

func (m *ChangeEipBandwidthRequest_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEipBandwidthRequest_Input.Unmarshal(m, b)
}
func (m *ChangeEipBandwidthRequest_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEipBandwidthRequest_Input.Marshal(b, m, deterministic)
}
func (m *ChangeEipBandwidthRequest_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEipBandwidthRequest_Input.Merge(m, src)
}
func (m *ChangeEipBandwidthRequest_Input) XXX_Size() int {
	return xxx_messageInfo_ChangeEipBandwidthRequest_Input.Size(m)
}
func (m *ChangeEipBandwidthRequest_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEipBandwidthRequest_Input.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEipBandwidthRequest_Input proto.InternalMessageInfo

func (m *ChangeEipBandwidthRequest_Input) GetEipUuid() string {
	if m != nil {
		return m.EipUuid
	}
	return ""
}

func (m *ChangeEipBandwidthRequest_Input) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *ChangeEipBandwidthRequest_Input) GetChargeWithFlow() bool {
	if m != nil {
		return m.ChargeWithFlow
	}
	return false
}

type ChangeEipBandwidthResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChangeEipBandwidthResponse) Reset()         { *m = ChangeEipBandwidthResponse{} }
func (m *ChangeEipBandwidthResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeEipBandwidthResponse) ProtoMessage()    {}
func (*ChangeEipBandwidthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{10}
}

func (m *ChangeEipBandwidthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEipBandwidthResponse.Unmarshal(m, b)
}
func (m *ChangeEipBandwidthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEipBandwidthResponse.Marshal(b, m, deterministic)
}
func (m *ChangeEipBandwidthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEipBandwidthResponse.Merge(m, src)
}
func (m *ChangeEipBandwidthResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeEipBandwidthResponse.Size(m)
}
func (m *ChangeEipBandwidthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEipBandwidthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEipBandwidthResponse proto.InternalMessageInfo

func (m *ChangeEipBandwidthResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ChangeEipBandwidthResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteEipRequest struct {
	Header               *v1.Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Eip                  []*DeleteEipRequest_Input `protobuf:"bytes,2,rep,name=eip,proto3" json:"eip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DeleteEipRequest) Reset()         { *m = DeleteEipRequest{} }
func (m *DeleteEipRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEipRequest) ProtoMessage()    {}
func (*DeleteEipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{11}
}

func (m *DeleteEipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEipRequest.Unmarshal(m, b)
}
func (m *DeleteEipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEipRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEipRequest.Merge(m, src)
}
func (m *DeleteEipRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEipRequest.Size(m)
}
func (m *DeleteEipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEipRequest proto.InternalMessageInfo

func (m *DeleteEipRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteEipRequest) GetEip() []*DeleteEipRequest_Input {
	if m != nil {
		return m.Eip
	}
	return nil
}

type DeleteEipRequest_Input struct {
	EipUuid              string   `protobuf:"bytes,1,opt,name=eipUuid,proto3" json:"eipUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEipRequest_Input) Reset()         { *m = DeleteEipRequest_Input{} }
func (m *DeleteEipRequest_Input) String() string { return proto.CompactTextString(m) }
func (*DeleteEipRequest_Input) ProtoMessage()    {}
func (*DeleteEipRequest_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{11, 0}
}

func (m *DeleteEipRequest_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEipRequest_Input.Unmarshal(m, b)
}
func (m *DeleteEipRequest_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEipRequest_Input.Marshal(b, m, deterministic)
}
func (m *DeleteEipRequest_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEipRequest_Input.Merge(m, src)
}
func (m *DeleteEipRequest_Input) XXX_Size() int {
	return xxx_messageInfo_DeleteEipRequest_Input.Size(m)
}
func (m *DeleteEipRequest_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEipRequest_Input.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEipRequest_Input proto.InternalMessageInfo

func (m *DeleteEipRequest_Input) GetEipUuid() string {
	if m != nil {
		return m.EipUuid
	}
	return ""
}

type DeleteEipResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteEipResponse) Reset()         { *m = DeleteEipResponse{} }
func (m *DeleteEipResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEipResponse) ProtoMessage()    {}
func (*DeleteEipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{12}
}

func (m *DeleteEipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEipResponse.Unmarshal(m, b)
}
func (m *DeleteEipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEipResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEipResponse.Merge(m, src)
}
func (m *DeleteEipResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEipResponse.Size(m)
}
func (m *DeleteEipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEipResponse proto.InternalMessageInfo

func (m *DeleteEipResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *DeleteEipResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExpungeEipRequest struct {
	Header               *v1.Header                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Eip                  []*ExpungeEipRequest_Input `protobuf:"bytes,2,rep,name=eip,proto3" json:"eip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ExpungeEipRequest) Reset()         { *m = ExpungeEipRequest{} }
func (m *ExpungeEipRequest) String() string { return proto.CompactTextString(m) }
func (*ExpungeEipRequest) ProtoMessage()    {}
func (*ExpungeEipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{13}
}

func (m *ExpungeEipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpungeEipRequest.Unmarshal(m, b)
}
func (m *ExpungeEipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpungeEipRequest.Marshal(b, m, deterministic)
}
func (m *ExpungeEipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpungeEipRequest.Merge(m, src)
}
func (m *ExpungeEipRequest) XXX_Size() int {
	return xxx_messageInfo_ExpungeEipRequest.Size(m)
}
func (m *ExpungeEipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpungeEipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpungeEipRequest proto.InternalMessageInfo

func (m *ExpungeEipRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ExpungeEipRequest) GetEip() []*ExpungeEipRequest_Input {
	if m != nil {
		return m.Eip
	}
	return nil
}

type ExpungeEipRequest_Input struct {
	EipUuid              string   `protobuf:"bytes,1,opt,name=eipUuid,proto3" json:"eipUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpungeEipRequest_Input) Reset()         { *m = ExpungeEipRequest_Input{} }
func (m *ExpungeEipRequest_Input) String() string { return proto.CompactTextString(m) }
func (*ExpungeEipRequest_Input) ProtoMessage()    {}
func (*ExpungeEipRequest_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{13, 0}
}

func (m *ExpungeEipRequest_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpungeEipRequest_Input.Unmarshal(m, b)
}
func (m *ExpungeEipRequest_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpungeEipRequest_Input.Marshal(b, m, deterministic)
}
func (m *ExpungeEipRequest_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpungeEipRequest_Input.Merge(m, src)
}
func (m *ExpungeEipRequest_Input) XXX_Size() int {
	return xxx_messageInfo_ExpungeEipRequest_Input.Size(m)
}
func (m *ExpungeEipRequest_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpungeEipRequest_Input.DiscardUnknown(m)
}

var xxx_messageInfo_ExpungeEipRequest_Input proto.InternalMessageInfo

func (m *ExpungeEipRequest_Input) GetEipUuid() string {
	if m != nil {
		return m.EipUuid
	}
	return ""
}

type ExpungeEipResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExpungeEipResponse) Reset()         { *m = ExpungeEipResponse{} }
func (m *ExpungeEipResponse) String() string { return proto.CompactTextString(m) }
func (*ExpungeEipResponse) ProtoMessage()    {}
func (*ExpungeEipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{14}
}

func (m *ExpungeEipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpungeEipResponse.Unmarshal(m, b)
}
func (m *ExpungeEipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpungeEipResponse.Marshal(b, m, deterministic)
}
func (m *ExpungeEipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpungeEipResponse.Merge(m, src)
}
func (m *ExpungeEipResponse) XXX_Size() int {
	return xxx_messageInfo_ExpungeEipResponse.Size(m)
}
func (m *ExpungeEipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpungeEipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExpungeEipResponse proto.InternalMessageInfo

func (m *ExpungeEipResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ExpungeEipResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type AttachEipToDc2Request struct {
	Header               *v1.Header                     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Eip                  []*AttachEipToDc2Request_Input `protobuf:"bytes,2,rep,name=eip,proto3" json:"eip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *AttachEipToDc2Request) Reset()         { *m = AttachEipToDc2Request{} }
func (m *AttachEipToDc2Request) String() string { return proto.CompactTextString(m) }
func (*AttachEipToDc2Request) ProtoMessage()    {}
func (*AttachEipToDc2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{15}
}

func (m *AttachEipToDc2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachEipToDc2Request.Unmarshal(m, b)
}
func (m *AttachEipToDc2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachEipToDc2Request.Marshal(b, m, deterministic)
}
func (m *AttachEipToDc2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachEipToDc2Request.Merge(m, src)
}
func (m *AttachEipToDc2Request) XXX_Size() int {
	return xxx_messageInfo_AttachEipToDc2Request.Size(m)
}
func (m *AttachEipToDc2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachEipToDc2Request.DiscardUnknown(m)
}

var xxx_messageInfo_AttachEipToDc2Request proto.InternalMessageInfo

func (m *AttachEipToDc2Request) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AttachEipToDc2Request) GetEip() []*AttachEipToDc2Request_Input {
	if m != nil {
		return m.Eip
	}
	return nil
}

type AttachEipToDc2Request_Input struct {
	EipUuid              string   `protobuf:"bytes,1,opt,name=eipUuid,proto3" json:"eipUuid,omitempty"`
	BindingUuid          string   `protobuf:"bytes,2,opt,name=bindingUuid,proto3" json:"bindingUuid,omitempty"`
	BindingType          string   `protobuf:"bytes,3,opt,name=bindingType,proto3" json:"bindingType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachEipToDc2Request_Input) Reset()         { *m = AttachEipToDc2Request_Input{} }
func (m *AttachEipToDc2Request_Input) String() string { return proto.CompactTextString(m) }
func (*AttachEipToDc2Request_Input) ProtoMessage()    {}
func (*AttachEipToDc2Request_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{15, 0}
}

func (m *AttachEipToDc2Request_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachEipToDc2Request_Input.Unmarshal(m, b)
}
func (m *AttachEipToDc2Request_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachEipToDc2Request_Input.Marshal(b, m, deterministic)
}
func (m *AttachEipToDc2Request_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachEipToDc2Request_Input.Merge(m, src)
}
func (m *AttachEipToDc2Request_Input) XXX_Size() int {
	return xxx_messageInfo_AttachEipToDc2Request_Input.Size(m)
}
func (m *AttachEipToDc2Request_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachEipToDc2Request_Input.DiscardUnknown(m)
}

var xxx_messageInfo_AttachEipToDc2Request_Input proto.InternalMessageInfo

func (m *AttachEipToDc2Request_Input) GetEipUuid() string {
	if m != nil {
		return m.EipUuid
	}
	return ""
}

func (m *AttachEipToDc2Request_Input) GetBindingUuid() string {
	if m != nil {
		return m.BindingUuid
	}
	return ""
}

func (m *AttachEipToDc2Request_Input) GetBindingType() string {
	if m != nil {
		return m.BindingType
	}
	return ""
}

type AttachEipToDc2Response struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AttachEipToDc2Response) Reset()         { *m = AttachEipToDc2Response{} }
func (m *AttachEipToDc2Response) String() string { return proto.CompactTextString(m) }
func (*AttachEipToDc2Response) ProtoMessage()    {}
func (*AttachEipToDc2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{16}
}

func (m *AttachEipToDc2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachEipToDc2Response.Unmarshal(m, b)
}
func (m *AttachEipToDc2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachEipToDc2Response.Marshal(b, m, deterministic)
}
func (m *AttachEipToDc2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachEipToDc2Response.Merge(m, src)
}
func (m *AttachEipToDc2Response) XXX_Size() int {
	return xxx_messageInfo_AttachEipToDc2Response.Size(m)
}
func (m *AttachEipToDc2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachEipToDc2Response.DiscardUnknown(m)
}

var xxx_messageInfo_AttachEipToDc2Response proto.InternalMessageInfo

func (m *AttachEipToDc2Response) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *AttachEipToDc2Response) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DetachEipFromDc2Request struct {
	Header               *v1.Header                       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Eip                  []*DetachEipFromDc2Request_Input `protobuf:"bytes,2,rep,name=eip,proto3" json:"eip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *DetachEipFromDc2Request) Reset()         { *m = DetachEipFromDc2Request{} }
func (m *DetachEipFromDc2Request) String() string { return proto.CompactTextString(m) }
func (*DetachEipFromDc2Request) ProtoMessage()    {}
func (*DetachEipFromDc2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{17}
}

func (m *DetachEipFromDc2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachEipFromDc2Request.Unmarshal(m, b)
}
func (m *DetachEipFromDc2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachEipFromDc2Request.Marshal(b, m, deterministic)
}
func (m *DetachEipFromDc2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachEipFromDc2Request.Merge(m, src)
}
func (m *DetachEipFromDc2Request) XXX_Size() int {
	return xxx_messageInfo_DetachEipFromDc2Request.Size(m)
}
func (m *DetachEipFromDc2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachEipFromDc2Request.DiscardUnknown(m)
}

var xxx_messageInfo_DetachEipFromDc2Request proto.InternalMessageInfo

func (m *DetachEipFromDc2Request) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DetachEipFromDc2Request) GetEip() []*DetachEipFromDc2Request_Input {
	if m != nil {
		return m.Eip
	}
	return nil
}

type DetachEipFromDc2Request_Input struct {
	EipUuid              string   `protobuf:"bytes,1,opt,name=eipUuid,proto3" json:"eipUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachEipFromDc2Request_Input) Reset()         { *m = DetachEipFromDc2Request_Input{} }
func (m *DetachEipFromDc2Request_Input) String() string { return proto.CompactTextString(m) }
func (*DetachEipFromDc2Request_Input) ProtoMessage()    {}
func (*DetachEipFromDc2Request_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{17, 0}
}

func (m *DetachEipFromDc2Request_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachEipFromDc2Request_Input.Unmarshal(m, b)
}
func (m *DetachEipFromDc2Request_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachEipFromDc2Request_Input.Marshal(b, m, deterministic)
}
func (m *DetachEipFromDc2Request_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachEipFromDc2Request_Input.Merge(m, src)
}
func (m *DetachEipFromDc2Request_Input) XXX_Size() int {
	return xxx_messageInfo_DetachEipFromDc2Request_Input.Size(m)
}
func (m *DetachEipFromDc2Request_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachEipFromDc2Request_Input.DiscardUnknown(m)
}

var xxx_messageInfo_DetachEipFromDc2Request_Input proto.InternalMessageInfo

func (m *DetachEipFromDc2Request_Input) GetEipUuid() string {
	if m != nil {
		return m.EipUuid
	}
	return ""
}

type DetachEipFromDc2Response struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DetachEipFromDc2Response) Reset()         { *m = DetachEipFromDc2Response{} }
func (m *DetachEipFromDc2Response) String() string { return proto.CompactTextString(m) }
func (*DetachEipFromDc2Response) ProtoMessage()    {}
func (*DetachEipFromDc2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_65548ac4f7ee81f0, []int{18}
}

func (m *DetachEipFromDc2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachEipFromDc2Response.Unmarshal(m, b)
}
func (m *DetachEipFromDc2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachEipFromDc2Response.Marshal(b, m, deterministic)
}
func (m *DetachEipFromDc2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachEipFromDc2Response.Merge(m, src)
}
func (m *DetachEipFromDc2Response) XXX_Size() int {
	return xxx_messageInfo_DetachEipFromDc2Response.Size(m)
}
func (m *DetachEipFromDc2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachEipFromDc2Response.DiscardUnknown(m)
}

var xxx_messageInfo_DetachEipFromDc2Response proto.InternalMessageInfo

func (m *DetachEipFromDc2Response) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *DetachEipFromDc2Response) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ListEipResponse)(nil), "didi.cloud.compute.v1.ListEipResponse")
	proto.RegisterType((*ListEipCondition)(nil), "didi.cloud.compute.v1.ListEipCondition")
	proto.RegisterType((*ListEipRequest)(nil), "didi.cloud.compute.v1.ListEipRequest")
	proto.RegisterType((*GetEipTotalCntRequest)(nil), "didi.cloud.compute.v1.GetEipTotalCntRequest")
	proto.RegisterType((*GetEipTotalCntResponse)(nil), "didi.cloud.compute.v1.GetEipTotalCntResponse")
	proto.RegisterType((*GetEipByUuidRequest)(nil), "didi.cloud.compute.v1.GetEipByUuidRequest")
	proto.RegisterType((*GetEipByUuidResponse)(nil), "didi.cloud.compute.v1.GetEipByUuidResponse")
	proto.RegisterType((*CreateEipRequest)(nil), "didi.cloud.compute.v1.CreateEipRequest")
	proto.RegisterType((*CreateEipResponse)(nil), "didi.cloud.compute.v1.CreateEipResponse")
	proto.RegisterType((*ChangeEipBandwidthRequest)(nil), "didi.cloud.compute.v1.ChangeEipBandwidthRequest")
	proto.RegisterType((*ChangeEipBandwidthRequest_Input)(nil), "didi.cloud.compute.v1.ChangeEipBandwidthRequest.Input")
	proto.RegisterType((*ChangeEipBandwidthResponse)(nil), "didi.cloud.compute.v1.ChangeEipBandwidthResponse")
	proto.RegisterType((*DeleteEipRequest)(nil), "didi.cloud.compute.v1.DeleteEipRequest")
	proto.RegisterType((*DeleteEipRequest_Input)(nil), "didi.cloud.compute.v1.DeleteEipRequest.Input")
	proto.RegisterType((*DeleteEipResponse)(nil), "didi.cloud.compute.v1.DeleteEipResponse")
	proto.RegisterType((*ExpungeEipRequest)(nil), "didi.cloud.compute.v1.ExpungeEipRequest")
	proto.RegisterType((*ExpungeEipRequest_Input)(nil), "didi.cloud.compute.v1.ExpungeEipRequest.Input")
	proto.RegisterType((*ExpungeEipResponse)(nil), "didi.cloud.compute.v1.ExpungeEipResponse")
	proto.RegisterType((*AttachEipToDc2Request)(nil), "didi.cloud.compute.v1.AttachEipToDc2Request")
	proto.RegisterType((*AttachEipToDc2Request_Input)(nil), "didi.cloud.compute.v1.AttachEipToDc2Request.Input")
	proto.RegisterType((*AttachEipToDc2Response)(nil), "didi.cloud.compute.v1.AttachEipToDc2Response")
	proto.RegisterType((*DetachEipFromDc2Request)(nil), "didi.cloud.compute.v1.DetachEipFromDc2Request")
	proto.RegisterType((*DetachEipFromDc2Request_Input)(nil), "didi.cloud.compute.v1.DetachEipFromDc2Request.Input")
	proto.RegisterType((*DetachEipFromDc2Response)(nil), "didi.cloud.compute.v1.DetachEipFromDc2Response")
}

func init() { proto.RegisterFile("compute/v1/eip.proto", fileDescriptor_65548ac4f7ee81f0) }

var fileDescriptor_65548ac4f7ee81f0 = []byte{
	// 1182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xd7, 0xda, 0x71, 0x12, 0xbf, 0x54, 0x21, 0x1d, 0xf2, 0x67, 0xbb, 0x4d, 0x4a, 0xd8, 0x92,
	0xd6, 0xfc, 0xc9, 0x2e, 0x36, 0x15, 0x1c, 0x38, 0x00, 0xb1, 0x1d, 0x1a, 0x84, 0xaa, 0x6a, 0x55,
	0x8a, 0x84, 0x72, 0x59, 0xef, 0x4e, 0xed, 0x51, 0xed, 0x9d, 0xc5, 0x3b, 0x9b, 0x60, 0xa8, 0x38,
	0x54, 0x08, 0x38, 0xd3, 0x03, 0xe2, 0xc2, 0x19, 0x55, 0x7c, 0x00, 0xc4, 0x47, 0xe0, 0xda, 0x0b,
	0x1f, 0x80, 0x0f, 0xd1, 0x23, 0x9a, 0xd9, 0xb1, 0xbd, 0xbb, 0xd9, 0xad, 0xed, 0x5a, 0xf2, 0xc9,
	0x7e, 0x33, 0x6f, 0xde, 0xfb, 0xcd, 0xef, 0xfd, 0x99, 0x67, 0xc3, 0xa6, 0x43, 0x7b, 0x7e, 0xc8,
	0xb0, 0x79, 0x56, 0x35, 0x31, 0xf1, 0x0d, 0xbf, 0x4f, 0x19, 0x45, 0x5b, 0x2e, 0x71, 0x89, 0xe1,
	0x74, 0x69, 0xe8, 0x1a, 0x52, 0xc1, 0x38, 0xab, 0x6a, 0xa8, 0x65, 0x07, 0x42, 0x93, 0x7f, 0x46,
	0xaa, 0xda, 0x4e, 0xcc, 0x80, 0x43, 0x7b, 0x3d, 0xea, 0xc9, 0x8d, 0xdd, 0x36, 0xa5, 0xed, 0x2e,
	0x36, 0x6d, 0x9f, 0x98, 0xb6, 0xe7, 0x51, 0x66, 0x33, 0x42, 0xbd, 0x20, 0xda, 0xd5, 0xcf, 0xe0,
	0x95, 0xcf, 0x49, 0xc0, 0x9a, 0xc4, 0xb7, 0x70, 0xe0, 0x53, 0x2f, 0xc0, 0xc8, 0x84, 0x12, 0xee,
	0xf7, 0x69, 0x5f, 0x55, 0xf6, 0x95, 0xca, 0x5a, 0xed, 0x8a, 0x11, 0x03, 0x21, 0x1c, 0x9e, 0x55,
	0x8d, 0x26, 0x57, 0xb0, 0x22, 0x3d, 0x54, 0x83, 0x25, 0xd7, 0x66, 0xb6, 0x5a, 0xd8, 0x2f, 0x56,
	0xd6, 0x6a, 0xd7, 0x8c, 0x4c, 0xd0, 0x46, 0x93, 0xf8, 0x27, 0xde, 0x03, 0x6a, 0x09, 0x5d, 0xfd,
	0x6f, 0x05, 0x36, 0xa4, 0xe3, 0x3a, 0xf5, 0x5c, 0xc2, 0x31, 0xa1, 0x0d, 0x28, 0x62, 0xe2, 0x0b,
	0xbf, 0x65, 0x8b, 0x7f, 0x45, 0x1a, 0xac, 0x62, 0xe2, 0x7f, 0x11, 0x12, 0x37, 0x10, 0xe6, 0xcb,
	0xd6, 0x48, 0x46, 0x37, 0x60, 0x1d, 0x13, 0xff, 0x0e, 0x65, 0x9f, 0x30, 0x66, 0x3b, 0x1d, 0xec,
	0xaa, 0xc5, 0x7d, 0xa5, 0xb2, 0x6a, 0xa5, 0x56, 0x91, 0x0a, 0x2b, 0xae, 0x53, 0xe3, 0x67, 0xd4,
	0x25, 0x61, 0x79, 0x28, 0xca, 0x9d, 0x3b, 0x76, 0x0f, 0xab, 0xa5, 0xd1, 0x0e, 0x17, 0xd1, 0x2e,
	0x94, 0x5b, 0xb6, 0xe7, 0x9e, 0x13, 0x97, 0x75, 0xd4, 0xe5, 0x7d, 0xa5, 0x52, 0xb2, 0xc6, 0x0b,
	0xfa, 0x33, 0x05, 0xd6, 0x47, 0xac, 0x7d, 0x1d, 0xe2, 0x80, 0xa1, 0x1a, 0x2c, 0x77, 0xb0, 0xed,
	0xe2, 0x21, 0x6b, 0x5a, 0x16, 0x6b, 0xb7, 0x85, 0x86, 0x25, 0x35, 0xd1, 0x26, 0x94, 0x02, 0x66,
	0xf7, 0x99, 0x5a, 0x10, 0x0e, 0x22, 0x81, 0xaf, 0x76, 0x49, 0x8f, 0x30, 0x71, 0x9b, 0x92, 0x15,
	0x09, 0x9c, 0x88, 0x80, 0xf4, 0xfc, 0x2e, 0x79, 0x30, 0x10, 0xb7, 0x58, 0xb5, 0x46, 0x32, 0x6a,
	0x42, 0xd9, 0x19, 0x72, 0x28, 0x2e, 0xb2, 0x56, 0xbb, 0x99, 0x13, 0x84, 0x34, 0xe5, 0xd6, 0xf8,
	0xa4, 0x3e, 0x80, 0xad, 0x4f, 0x31, 0xdf, 0xbd, 0x47, 0x99, 0xdd, 0xad, 0x7b, 0x6c, 0x9e, 0xbb,
	0xc9, 0x50, 0x16, 0xb2, 0x43, 0x59, 0x4c, 0x86, 0x52, 0x7f, 0xac, 0xc0, 0x76, 0xda, 0xf7, 0xcb,
	0x66, 0xe3, 0x07, 0x89, 0x6c, 0xbc, 0x9e, 0x43, 0xc4, 0xd0, 0x4f, 0x2c, 0x25, 0x1d, 0x78, 0x35,
	0xc2, 0x70, 0x34, 0xe0, 0xa8, 0xe6, 0xb9, 0xbd, 0x0a, 0x2b, 0xf2, 0x6e, 0x92, 0x81, 0xa1, 0xa8,
	0x7f, 0x07, 0x9b, 0x49, 0x27, 0x8b, 0x2c, 0xba, 0x7f, 0x0b, 0xb0, 0x51, 0xef, 0x63, 0x9b, 0xe1,
	0x39, 0x33, 0x77, 0x17, 0xca, 0xbe, 0x3d, 0xb8, 0x8b, 0xfb, 0x84, 0xba, 0x32, 0x7b, 0xc7, 0x0b,
	0x48, 0x87, 0x4b, 0x76, 0xc8, 0x68, 0x9d, 0x7a, 0x8c, 0x78, 0x21, 0x96, 0x65, 0x99, 0x58, 0xe3,
	0x59, 0xee, 0xd0, 0xd0, 0x63, 0x22, 0x99, 0x4b, 0x56, 0x24, 0xf0, 0x1c, 0x71, 0x68, 0xe8, 0x53,
	0xef, 0xc4, 0x95, 0x15, 0x39, 0x92, 0x11, 0x82, 0x25, 0x66, 0xb7, 0x03, 0x75, 0x59, 0xe4, 0x8e,
	0xf8, 0xce, 0x5b, 0x80, 0xd3, 0xb1, 0xfb, 0x6d, 0xfc, 0x25, 0x61, 0x9d, 0xe3, 0x2e, 0x3d, 0x57,
	0x57, 0xa2, 0x16, 0x90, 0x5c, 0x4d, 0x96, 0xf3, 0x6a, 0xaa, 0x9c, 0xd1, 0x3e, 0xac, 0xb5, 0x88,
	0xe7, 0x12, 0xaf, 0x2d, 0x22, 0x56, 0x16, 0x8e, 0xe3, 0x4b, 0x31, 0x8d, 0x7b, 0x03, 0x1f, 0xab,
	0x90, 0xd0, 0xe0, 0x4b, 0x7a, 0x08, 0x97, 0x63, 0xcc, 0xbe, 0x6c, 0x50, 0xcd, 0x44, 0x50, 0xaf,
	0x66, 0xe9, 0x7f, 0x46, 0x5b, 0xb1, 0x88, 0xfe, 0x5e, 0x80, 0x2b, 0xf5, 0x8e, 0xed, 0xb5, 0xb9,
	0xdf, 0xa3, 0xe1, 0x8d, 0xe6, 0x09, 0x6d, 0x3c, 0x04, 0x85, 0x54, 0x08, 0x6e, 0x47, 0x45, 0x5d,
	0x14, 0xe8, 0xde, 0xcf, 0x49, 0xb9, 0x5c, 0x38, 0xc6, 0x89, 0xe7, 0x87, 0x4c, 0x34, 0x03, 0xad,
	0x0d, 0x25, 0x21, 0xc5, 0x2b, 0x45, 0x49, 0x54, 0x4a, 0x32, 0x66, 0x85, 0x74, 0xcc, 0x2e, 0x46,
	0xbe, 0x98, 0x15, 0x79, 0xfd, 0x7b, 0xd0, 0xb2, 0x00, 0x2d, 0x2c, 0x40, 0x4f, 0x15, 0xd8, 0x68,
	0xe0, 0x2e, 0x9e, 0xbb, 0xe4, 0x3e, 0x1a, 0x36, 0x54, 0xee, 0xf8, 0x30, 0x87, 0xfb, 0xb4, 0xa7,
	0x38, 0xe5, 0xaf, 0x4f, 0xa4, 0x9c, 0x27, 0x71, 0xcc, 0xc2, 0xc2, 0x38, 0xfa, 0x53, 0x81, 0xcb,
	0xcd, 0x6f, 0xfc, 0x30, 0x8a, 0xd2, 0x3c, 0x24, 0x7d, 0x1c, 0x27, 0xc9, 0xc8, 0xeb, 0x89, 0x69,
	0x57, 0x33, 0xb2, 0x74, 0x06, 0x28, 0x6e, 0x62, 0x61, 0x34, 0x3d, 0x57, 0x60, 0x2b, 0x1a, 0x6a,
	0xc4, 0x3b, 0xd9, 0x70, 0x6a, 0xf3, 0x50, 0xd5, 0x88, 0x53, 0x55, 0xcb, 0xa1, 0x2a, 0xd3, 0x5d,
	0x9c, 0x2e, 0x3c, 0xb9, 0x8e, 0x53, 0xdd, 0xb5, 0x30, 0xb1, 0xbb, 0x16, 0x2f, 0x76, 0xd7, 0x6f,
	0x61, 0x3b, 0x0d, 0x65, 0x61, 0xb4, 0xff, 0xa5, 0xc0, 0x4e, 0x03, 0x4b, 0xe7, 0xc7, 0x7d, 0xda,
	0x9b, 0x93, 0xf8, 0xe3, 0x38, 0xf1, 0xb7, 0x72, 0x0b, 0x39, 0xd3, 0xe1, 0x8c, 0x99, 0xfa, 0x08,
	0xd4, 0x8b, 0x86, 0x16, 0x45, 0x5c, 0xed, 0x57, 0x80, 0x62, 0x93, 0xf8, 0xe8, 0x11, 0xac, 0xc8,
	0xb1, 0x13, 0x1d, 0xbc, 0x78, 0x2c, 0x95, 0xb7, 0xd4, 0x6e, 0x4c, 0x52, 0x8b, 0xee, 0xa0, 0xeb,
	0x8f, 0x9f, 0xfd, 0xf7, 0xa4, 0xb0, 0xab, 0x6b, 0x2e, 0x11, 0xba, 0x26, 0x31, 0x3d, 0xcc, 0xce,
	0x69, 0xff, 0x21, 0xff, 0x0d, 0x65, 0x76, 0x49, 0xc0, 0xd0, 0x2f, 0x0a, 0xac, 0x27, 0x47, 0x4b,
	0xf4, 0x4e, 0x8e, 0xf9, 0xcc, 0xe9, 0x57, 0x3b, 0x9c, 0x52, 0x5b, 0x62, 0xba, 0x2e, 0x30, 0xed,
	0xe9, 0x57, 0xb3, 0x31, 0x45, 0x73, 0xce, 0x8f, 0x0a, 0x5c, 0x8a, 0x8f, 0x81, 0xe8, 0xad, 0x17,
	0x3a, 0x49, 0x0c, 0xa4, 0xda, 0xdb, 0x53, 0xe9, 0x4a, 0x38, 0x7b, 0x02, 0xce, 0x0e, 0xff, 0x25,
	0x99, 0x01, 0x07, 0xfd, 0xa0, 0x40, 0x79, 0x34, 0xb7, 0xa0, 0xbc, 0x5f, 0x0d, 0xe9, 0x99, 0x51,
	0xab, 0x4c, 0x56, 0x94, 0xfe, 0xdf, 0x10, 0xfe, 0xaf, 0xe9, 0xbb, 0xd9, 0x74, 0xd8, 0x41, 0x40,
	0xda, 0x1e, 0xfa, 0x43, 0x01, 0x74, 0xf1, 0x99, 0x46, 0xef, 0xce, 0x3a, 0x62, 0x68, 0xd5, 0x19,
	0x4e, 0x48, 0x84, 0x87, 0x02, 0xe1, 0x4d, 0xfd, 0x20, 0x27, 0x60, 0xe2, 0xe4, 0x18, 0x13, 0x67,
	0x6c, 0xf4, 0x48, 0xe6, 0x32, 0x96, 0x7e, 0x88, 0x73, 0x19, 0xbb, 0xf0, 0xde, 0x4e, 0x62, 0xcc,
	0x15, 0x07, 0xd0, 0xcf, 0x0a, 0xc0, 0xf8, 0x15, 0x42, 0x95, 0x69, 0xdf, 0x3a, 0xed, 0xcd, 0x29,
	0x34, 0x25, 0x92, 0x03, 0x81, 0xe4, 0x35, 0x7d, 0x2f, 0x1b, 0x09, 0x8e, 0x4e, 0xa0, 0x27, 0x0a,
	0xac, 0x27, 0xbb, 0x73, 0x6e, 0x85, 0x65, 0xbe, 0x27, 0xb9, 0x15, 0x96, 0xdd, 0xf2, 0x27, 0xa6,
	0x94, 0x38, 0x85, 0x7e, 0x13, 0x83, 0x57, 0xb2, 0xf9, 0x21, 0x63, 0xb6, 0x76, 0xab, 0x99, 0x53,
	0xeb, 0x4f, 0x1b, 0x3c, 0x7e, 0xee, 0xe8, 0x27, 0x05, 0xb6, 0x1d, 0xda, 0x13, 0xc6, 0x07, 0xa1,
	0x17, 0xb3, 0x7c, 0x57, 0xf9, 0xea, 0x56, 0x9b, 0xb0, 0x4e, 0xd8, 0xe2, 0x8b, 0xa6, 0x54, 0x18,
	0x7e, 0x1e, 0xb6, 0xe9, 0x61, 0xe0, 0x3e, 0x34, 0xc7, 0x7f, 0xf5, 0x7c, 0x28, 0xbf, 0x3e, 0x57,
	0x94, 0xa7, 0x85, 0x9d, 0x06, 0x07, 0xdb, 0x88, 0x3c, 0x1b, 0x75, 0x69, 0xf4, 0x7e, 0xf5, 0x9f,
	0x68, 0xe7, 0x54, 0xee, 0x9c, 0xca, 0x9d, 0xd3, 0xfb, 0xd5, 0xd6, 0xb2, 0xf8, 0x17, 0xe8, 0xbd,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x36, 0xbe, 0x19, 0x7f, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EipClient is the client API for Eip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EipClient interface {
	// 获取eip列表
	ListEip(ctx context.Context, in *ListEipRequest, opts ...grpc.CallOption) (*ListEipResponse, error)
	// 获取eip数量
	GetEipTotalCnt(ctx context.Context, in *GetEipTotalCntRequest, opts ...grpc.CallOption) (*GetEipTotalCntResponse, error)
	// 根据uuid获取eip
	GetEipByUuid(ctx context.Context, in *GetEipByUuidRequest, opts ...grpc.CallOption) (*GetEipByUuidResponse, error)
	// 创建eip
	CreateEip(ctx context.Context, in *CreateEipRequest, opts ...grpc.CallOption) (*CreateEipResponse, error)
	// 更改eip带宽
	ChangeEipBandwidth(ctx context.Context, in *ChangeEipBandwidthRequest, opts ...grpc.CallOption) (*ChangeEipBandwidthResponse, error)
	// 删除eip
	DeleteEip(ctx context.Context, in *DeleteEipRequest, opts ...grpc.CallOption) (*DeleteEipResponse, error)
	// 销毁eip
	ExpungeEip(ctx context.Context, in *ExpungeEipRequest, opts ...grpc.CallOption) (*ExpungeEipResponse, error)
	// 绑定eip到dc2
	AttachEipToDc2(ctx context.Context, in *AttachEipToDc2Request, opts ...grpc.CallOption) (*AttachEipToDc2Response, error)
	// 从dc2解绑eip
	DetachEipFromDc2(ctx context.Context, in *DetachEipFromDc2Request, opts ...grpc.CallOption) (*DetachEipFromDc2Response, error)
}

type eipClient struct {
	cc *grpc.ClientConn
}

func NewEipClient(cc *grpc.ClientConn) EipClient {
	return &eipClient{cc}
}

func (c *eipClient) ListEip(ctx context.Context, in *ListEipRequest, opts ...grpc.CallOption) (*ListEipResponse, error) {
	out := new(ListEipResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/ListEip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) GetEipTotalCnt(ctx context.Context, in *GetEipTotalCntRequest, opts ...grpc.CallOption) (*GetEipTotalCntResponse, error) {
	out := new(GetEipTotalCntResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/GetEipTotalCnt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) GetEipByUuid(ctx context.Context, in *GetEipByUuidRequest, opts ...grpc.CallOption) (*GetEipByUuidResponse, error) {
	out := new(GetEipByUuidResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/GetEipByUuid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) CreateEip(ctx context.Context, in *CreateEipRequest, opts ...grpc.CallOption) (*CreateEipResponse, error) {
	out := new(CreateEipResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/CreateEip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) ChangeEipBandwidth(ctx context.Context, in *ChangeEipBandwidthRequest, opts ...grpc.CallOption) (*ChangeEipBandwidthResponse, error) {
	out := new(ChangeEipBandwidthResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/ChangeEipBandwidth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) DeleteEip(ctx context.Context, in *DeleteEipRequest, opts ...grpc.CallOption) (*DeleteEipResponse, error) {
	out := new(DeleteEipResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/DeleteEip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) ExpungeEip(ctx context.Context, in *ExpungeEipRequest, opts ...grpc.CallOption) (*ExpungeEipResponse, error) {
	out := new(ExpungeEipResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/ExpungeEip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) AttachEipToDc2(ctx context.Context, in *AttachEipToDc2Request, opts ...grpc.CallOption) (*AttachEipToDc2Response, error) {
	out := new(AttachEipToDc2Response)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/AttachEipToDc2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eipClient) DetachEipFromDc2(ctx context.Context, in *DetachEipFromDc2Request, opts ...grpc.CallOption) (*DetachEipFromDc2Response, error) {
	out := new(DetachEipFromDc2Response)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Eip/DetachEipFromDc2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EipServer is the server API for Eip service.
type EipServer interface {
	// 获取eip列表
	ListEip(context.Context, *ListEipRequest) (*ListEipResponse, error)
	// 获取eip数量
	GetEipTotalCnt(context.Context, *GetEipTotalCntRequest) (*GetEipTotalCntResponse, error)
	// 根据uuid获取eip
	GetEipByUuid(context.Context, *GetEipByUuidRequest) (*GetEipByUuidResponse, error)
	// 创建eip
	CreateEip(context.Context, *CreateEipRequest) (*CreateEipResponse, error)
	// 更改eip带宽
	ChangeEipBandwidth(context.Context, *ChangeEipBandwidthRequest) (*ChangeEipBandwidthResponse, error)
	// 删除eip
	DeleteEip(context.Context, *DeleteEipRequest) (*DeleteEipResponse, error)
	// 销毁eip
	ExpungeEip(context.Context, *ExpungeEipRequest) (*ExpungeEipResponse, error)
	// 绑定eip到dc2
	AttachEipToDc2(context.Context, *AttachEipToDc2Request) (*AttachEipToDc2Response, error)
	// 从dc2解绑eip
	DetachEipFromDc2(context.Context, *DetachEipFromDc2Request) (*DetachEipFromDc2Response, error)
}

// UnimplementedEipServer can be embedded to have forward compatible implementations.
type UnimplementedEipServer struct {
}

func (*UnimplementedEipServer) ListEip(ctx context.Context, req *ListEipRequest) (*ListEipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEip not implemented")
}
func (*UnimplementedEipServer) GetEipTotalCnt(ctx context.Context, req *GetEipTotalCntRequest) (*GetEipTotalCntResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEipTotalCnt not implemented")
}
func (*UnimplementedEipServer) GetEipByUuid(ctx context.Context, req *GetEipByUuidRequest) (*GetEipByUuidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEipByUuid not implemented")
}
func (*UnimplementedEipServer) CreateEip(ctx context.Context, req *CreateEipRequest) (*CreateEipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEip not implemented")
}
func (*UnimplementedEipServer) ChangeEipBandwidth(ctx context.Context, req *ChangeEipBandwidthRequest) (*ChangeEipBandwidthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEipBandwidth not implemented")
}
func (*UnimplementedEipServer) DeleteEip(ctx context.Context, req *DeleteEipRequest) (*DeleteEipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEip not implemented")
}
func (*UnimplementedEipServer) ExpungeEip(ctx context.Context, req *ExpungeEipRequest) (*ExpungeEipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpungeEip not implemented")
}
func (*UnimplementedEipServer) AttachEipToDc2(ctx context.Context, req *AttachEipToDc2Request) (*AttachEipToDc2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachEipToDc2 not implemented")
}
func (*UnimplementedEipServer) DetachEipFromDc2(ctx context.Context, req *DetachEipFromDc2Request) (*DetachEipFromDc2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetachEipFromDc2 not implemented")
}

func RegisterEipServer(s *grpc.Server, srv EipServer) {
	s.RegisterService(&_Eip_serviceDesc, srv)
}

func _Eip_ListEip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).ListEip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/ListEip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).ListEip(ctx, req.(*ListEipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_GetEipTotalCnt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEipTotalCntRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).GetEipTotalCnt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/GetEipTotalCnt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).GetEipTotalCnt(ctx, req.(*GetEipTotalCntRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_GetEipByUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEipByUuidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).GetEipByUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/GetEipByUuid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).GetEipByUuid(ctx, req.(*GetEipByUuidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_CreateEip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).CreateEip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/CreateEip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).CreateEip(ctx, req.(*CreateEipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_ChangeEipBandwidth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEipBandwidthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).ChangeEipBandwidth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/ChangeEipBandwidth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).ChangeEipBandwidth(ctx, req.(*ChangeEipBandwidthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_DeleteEip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).DeleteEip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/DeleteEip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).DeleteEip(ctx, req.(*DeleteEipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_ExpungeEip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpungeEipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).ExpungeEip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/ExpungeEip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).ExpungeEip(ctx, req.(*ExpungeEipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_AttachEipToDc2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachEipToDc2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).AttachEipToDc2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/AttachEipToDc2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).AttachEipToDc2(ctx, req.(*AttachEipToDc2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Eip_DetachEipFromDc2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachEipFromDc2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EipServer).DetachEipFromDc2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Eip/DetachEipFromDc2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EipServer).DetachEipFromDc2(ctx, req.(*DetachEipFromDc2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Eip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didi.cloud.compute.v1.Eip",
	HandlerType: (*EipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEip",
			Handler:    _Eip_ListEip_Handler,
		},
		{
			MethodName: "GetEipTotalCnt",
			Handler:    _Eip_GetEipTotalCnt_Handler,
		},
		{
			MethodName: "GetEipByUuid",
			Handler:    _Eip_GetEipByUuid_Handler,
		},
		{
			MethodName: "CreateEip",
			Handler:    _Eip_CreateEip_Handler,
		},
		{
			MethodName: "ChangeEipBandwidth",
			Handler:    _Eip_ChangeEipBandwidth_Handler,
		},
		{
			MethodName: "DeleteEip",
			Handler:    _Eip_DeleteEip_Handler,
		},
		{
			MethodName: "ExpungeEip",
			Handler:    _Eip_ExpungeEip_Handler,
		},
		{
			MethodName: "AttachEipToDc2",
			Handler:    _Eip_AttachEipToDc2_Handler,
		},
		{
			MethodName: "DetachEipFromDc2",
			Handler:    _Eip_DetachEipFromDc2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute/v1/eip.proto",
}
