// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compute/v1/snap.proto

package compute // import "github.com/didiyun/didiyun-go-sdk/compute/v1"

/*
snap Service

snap Service API consists of a single service which returns
a message.
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1 "github.com/didiyun/didiyun-go-sdk/base/v1"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListSnapshotRequest struct {
	Header               *v1.Header             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Start                int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Limit                int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Simplify             bool                   `protobuf:"varint,4,opt,name=simplify,proto3" json:"simplify,omitempty"`
	Condition            *ListSnapshotCondition `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListSnapshotRequest) Reset()         { *m = ListSnapshotRequest{} }
func (m *ListSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*ListSnapshotRequest) ProtoMessage()    {}
func (*ListSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{0}
}
func (m *ListSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSnapshotRequest.Unmarshal(m, b)
}
func (m *ListSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSnapshotRequest.Marshal(b, m, deterministic)
}
func (dst *ListSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSnapshotRequest.Merge(dst, src)
}
func (m *ListSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_ListSnapshotRequest.Size(m)
}
func (m *ListSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSnapshotRequest proto.InternalMessageInfo

func (m *ListSnapshotRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ListSnapshotRequest) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ListSnapshotRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListSnapshotRequest) GetSimplify() bool {
	if m != nil {
		return m.Simplify
	}
	return false
}

func (m *ListSnapshotRequest) GetCondition() *ListSnapshotCondition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type ListSnapshotCondition struct {
	EbsUuid              string   `protobuf:"bytes,1,opt,name=ebsUuid,proto3" json:"ebsUuid,omitempty"`
	SnapName             string   `protobuf:"bytes,2,opt,name=snapName,proto3" json:"snapName,omitempty"`
	Dc2Uuid              string   `protobuf:"bytes,3,opt,name=dc2Uuid,proto3" json:"dc2Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSnapshotCondition) Reset()         { *m = ListSnapshotCondition{} }
func (m *ListSnapshotCondition) String() string { return proto.CompactTextString(m) }
func (*ListSnapshotCondition) ProtoMessage()    {}
func (*ListSnapshotCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{1}
}
func (m *ListSnapshotCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSnapshotCondition.Unmarshal(m, b)
}
func (m *ListSnapshotCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSnapshotCondition.Marshal(b, m, deterministic)
}
func (dst *ListSnapshotCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSnapshotCondition.Merge(dst, src)
}
func (m *ListSnapshotCondition) XXX_Size() int {
	return xxx_messageInfo_ListSnapshotCondition.Size(m)
}
func (m *ListSnapshotCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSnapshotCondition.DiscardUnknown(m)
}

var xxx_messageInfo_ListSnapshotCondition proto.InternalMessageInfo

func (m *ListSnapshotCondition) GetEbsUuid() string {
	if m != nil {
		return m.EbsUuid
	}
	return ""
}

func (m *ListSnapshotCondition) GetSnapName() string {
	if m != nil {
		return m.SnapName
	}
	return ""
}

func (m *ListSnapshotCondition) GetDc2Uuid() string {
	if m != nil {
		return m.Dc2Uuid
	}
	return ""
}

type ListSnapshotResponse struct {
	Error                *v1.Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*SnapInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListSnapshotResponse) Reset()         { *m = ListSnapshotResponse{} }
func (m *ListSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*ListSnapshotResponse) ProtoMessage()    {}
func (*ListSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{2}
}
func (m *ListSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSnapshotResponse.Unmarshal(m, b)
}
func (m *ListSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSnapshotResponse.Marshal(b, m, deterministic)
}
func (dst *ListSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSnapshotResponse.Merge(dst, src)
}
func (m *ListSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_ListSnapshotResponse.Size(m)
}
func (m *ListSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSnapshotResponse proto.InternalMessageInfo

func (m *ListSnapshotResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListSnapshotResponse) GetData() []*SnapInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetSnapshotTotalCntRequest struct {
	Header               *v1.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EbsUuid              string     `protobuf:"bytes,2,opt,name=ebsUuid,proto3" json:"ebsUuid,omitempty"`
	SnapName             string     `protobuf:"bytes,3,opt,name=snapName,proto3" json:"snapName,omitempty"`
	Dc2Uuid              string     `protobuf:"bytes,4,opt,name=dc2Uuid,proto3" json:"dc2Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetSnapshotTotalCntRequest) Reset()         { *m = GetSnapshotTotalCntRequest{} }
func (m *GetSnapshotTotalCntRequest) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotTotalCntRequest) ProtoMessage()    {}
func (*GetSnapshotTotalCntRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{3}
}
func (m *GetSnapshotTotalCntRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotTotalCntRequest.Unmarshal(m, b)
}
func (m *GetSnapshotTotalCntRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotTotalCntRequest.Marshal(b, m, deterministic)
}
func (dst *GetSnapshotTotalCntRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotTotalCntRequest.Merge(dst, src)
}
func (m *GetSnapshotTotalCntRequest) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotTotalCntRequest.Size(m)
}
func (m *GetSnapshotTotalCntRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotTotalCntRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotTotalCntRequest proto.InternalMessageInfo

func (m *GetSnapshotTotalCntRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetSnapshotTotalCntRequest) GetEbsUuid() string {
	if m != nil {
		return m.EbsUuid
	}
	return ""
}

func (m *GetSnapshotTotalCntRequest) GetSnapName() string {
	if m != nil {
		return m.SnapName
	}
	return ""
}

func (m *GetSnapshotTotalCntRequest) GetDc2Uuid() string {
	if m != nil {
		return m.Dc2Uuid
	}
	return ""
}

type GetSnapshotTotalCntResponse struct {
	Error                *v1.Error       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*TotalCntInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetSnapshotTotalCntResponse) Reset()         { *m = GetSnapshotTotalCntResponse{} }
func (m *GetSnapshotTotalCntResponse) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotTotalCntResponse) ProtoMessage()    {}
func (*GetSnapshotTotalCntResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{4}
}
func (m *GetSnapshotTotalCntResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotTotalCntResponse.Unmarshal(m, b)
}
func (m *GetSnapshotTotalCntResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotTotalCntResponse.Marshal(b, m, deterministic)
}
func (dst *GetSnapshotTotalCntResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotTotalCntResponse.Merge(dst, src)
}
func (m *GetSnapshotTotalCntResponse) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotTotalCntResponse.Size(m)
}
func (m *GetSnapshotTotalCntResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotTotalCntResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotTotalCntResponse proto.InternalMessageInfo

func (m *GetSnapshotTotalCntResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetSnapshotTotalCntResponse) GetData() []*TotalCntInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateSnapshotRequest struct {
	Header               *v1.Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Dc2Uuid              string     `protobuf:"bytes,2,opt,name=dc2Uuid,proto3" json:"dc2Uuid,omitempty"`
	EbsUuid              string     `protobuf:"bytes,3,opt,name=ebsUuid,proto3" json:"ebsUuid,omitempty"`
	SnapName             string     `protobuf:"bytes,4,opt,name=snapName,proto3" json:"snapName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateSnapshotRequest) Reset()         { *m = CreateSnapshotRequest{} }
func (m *CreateSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotRequest) ProtoMessage()    {}
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{5}
}
func (m *CreateSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSnapshotRequest.Unmarshal(m, b)
}
func (m *CreateSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSnapshotRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSnapshotRequest.Merge(dst, src)
}
func (m *CreateSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSnapshotRequest.Size(m)
}
func (m *CreateSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSnapshotRequest proto.InternalMessageInfo

func (m *CreateSnapshotRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateSnapshotRequest) GetDc2Uuid() string {
	if m != nil {
		return m.Dc2Uuid
	}
	return ""
}

func (m *CreateSnapshotRequest) GetEbsUuid() string {
	if m != nil {
		return m.EbsUuid
	}
	return ""
}

func (m *CreateSnapshotRequest) GetSnapName() string {
	if m != nil {
		return m.SnapName
	}
	return ""
}

type CreateSnapshotResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateSnapshotResponse) Reset()         { *m = CreateSnapshotResponse{} }
func (m *CreateSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSnapshotResponse) ProtoMessage()    {}
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{6}
}
func (m *CreateSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSnapshotResponse.Unmarshal(m, b)
}
func (m *CreateSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSnapshotResponse.Marshal(b, m, deterministic)
}
func (dst *CreateSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSnapshotResponse.Merge(dst, src)
}
func (m *CreateSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSnapshotResponse.Size(m)
}
func (m *CreateSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSnapshotResponse proto.InternalMessageInfo

func (m *CreateSnapshotResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreateSnapshotResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteSnapshotRequest struct {
	Header               *v1.Header                     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Snap                 []*DeleteSnapshotRequest_Input `protobuf:"bytes,2,rep,name=snap,proto3" json:"snap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DeleteSnapshotRequest) Reset()         { *m = DeleteSnapshotRequest{} }
func (m *DeleteSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSnapshotRequest) ProtoMessage()    {}
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{7}
}
func (m *DeleteSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSnapshotRequest.Unmarshal(m, b)
}
func (m *DeleteSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSnapshotRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSnapshotRequest.Merge(dst, src)
}
func (m *DeleteSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSnapshotRequest.Size(m)
}
func (m *DeleteSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSnapshotRequest proto.InternalMessageInfo

func (m *DeleteSnapshotRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeleteSnapshotRequest) GetSnap() []*DeleteSnapshotRequest_Input {
	if m != nil {
		return m.Snap
	}
	return nil
}

type DeleteSnapshotRequest_Input struct {
	SnapUuid             string   `protobuf:"bytes,1,opt,name=snapUuid,proto3" json:"snapUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSnapshotRequest_Input) Reset()         { *m = DeleteSnapshotRequest_Input{} }
func (m *DeleteSnapshotRequest_Input) String() string { return proto.CompactTextString(m) }
func (*DeleteSnapshotRequest_Input) ProtoMessage()    {}
func (*DeleteSnapshotRequest_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{7, 0}
}
func (m *DeleteSnapshotRequest_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSnapshotRequest_Input.Unmarshal(m, b)
}
func (m *DeleteSnapshotRequest_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSnapshotRequest_Input.Marshal(b, m, deterministic)
}
func (dst *DeleteSnapshotRequest_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSnapshotRequest_Input.Merge(dst, src)
}
func (m *DeleteSnapshotRequest_Input) XXX_Size() int {
	return xxx_messageInfo_DeleteSnapshotRequest_Input.Size(m)
}
func (m *DeleteSnapshotRequest_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSnapshotRequest_Input.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSnapshotRequest_Input proto.InternalMessageInfo

func (m *DeleteSnapshotRequest_Input) GetSnapUuid() string {
	if m != nil {
		return m.SnapUuid
	}
	return ""
}

type DeleteSnapshotResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteSnapshotResponse) Reset()         { *m = DeleteSnapshotResponse{} }
func (m *DeleteSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSnapshotResponse) ProtoMessage()    {}
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{8}
}
func (m *DeleteSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSnapshotResponse.Unmarshal(m, b)
}
func (m *DeleteSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSnapshotResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSnapshotResponse.Merge(dst, src)
}
func (m *DeleteSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSnapshotResponse.Size(m)
}
func (m *DeleteSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSnapshotResponse proto.InternalMessageInfo

func (m *DeleteSnapshotResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *DeleteSnapshotResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type RevertSnapshotRequest struct {
	Header               *v1.Header                     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Snap                 []*RevertSnapshotRequest_Input `protobuf:"bytes,2,rep,name=snap,proto3" json:"snap,omitempty"`
	StopDc2              bool                           `protobuf:"varint,3,opt,name=stopDc2,proto3" json:"stopDc2,omitempty"`
	StartDc2             bool                           `protobuf:"varint,4,opt,name=startDc2,proto3" json:"startDc2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RevertSnapshotRequest) Reset()         { *m = RevertSnapshotRequest{} }
func (m *RevertSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*RevertSnapshotRequest) ProtoMessage()    {}
func (*RevertSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{9}
}
func (m *RevertSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevertSnapshotRequest.Unmarshal(m, b)
}
func (m *RevertSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevertSnapshotRequest.Marshal(b, m, deterministic)
}
func (dst *RevertSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevertSnapshotRequest.Merge(dst, src)
}
func (m *RevertSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_RevertSnapshotRequest.Size(m)
}
func (m *RevertSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevertSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevertSnapshotRequest proto.InternalMessageInfo

func (m *RevertSnapshotRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RevertSnapshotRequest) GetSnap() []*RevertSnapshotRequest_Input {
	if m != nil {
		return m.Snap
	}
	return nil
}

func (m *RevertSnapshotRequest) GetStopDc2() bool {
	if m != nil {
		return m.StopDc2
	}
	return false
}

func (m *RevertSnapshotRequest) GetStartDc2() bool {
	if m != nil {
		return m.StartDc2
	}
	return false
}

type RevertSnapshotRequest_Input struct {
	SnapUuid             string   `protobuf:"bytes,1,opt,name=snapUuid,proto3" json:"snapUuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevertSnapshotRequest_Input) Reset()         { *m = RevertSnapshotRequest_Input{} }
func (m *RevertSnapshotRequest_Input) String() string { return proto.CompactTextString(m) }
func (*RevertSnapshotRequest_Input) ProtoMessage()    {}
func (*RevertSnapshotRequest_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{9, 0}
}
func (m *RevertSnapshotRequest_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevertSnapshotRequest_Input.Unmarshal(m, b)
}
func (m *RevertSnapshotRequest_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevertSnapshotRequest_Input.Marshal(b, m, deterministic)
}
func (dst *RevertSnapshotRequest_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevertSnapshotRequest_Input.Merge(dst, src)
}
func (m *RevertSnapshotRequest_Input) XXX_Size() int {
	return xxx_messageInfo_RevertSnapshotRequest_Input.Size(m)
}
func (m *RevertSnapshotRequest_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_RevertSnapshotRequest_Input.DiscardUnknown(m)
}

var xxx_messageInfo_RevertSnapshotRequest_Input proto.InternalMessageInfo

func (m *RevertSnapshotRequest_Input) GetSnapUuid() string {
	if m != nil {
		return m.SnapUuid
	}
	return ""
}

type RevertSnapshotResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RevertSnapshotResponse) Reset()         { *m = RevertSnapshotResponse{} }
func (m *RevertSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*RevertSnapshotResponse) ProtoMessage()    {}
func (*RevertSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{10}
}
func (m *RevertSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevertSnapshotResponse.Unmarshal(m, b)
}
func (m *RevertSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevertSnapshotResponse.Marshal(b, m, deterministic)
}
func (dst *RevertSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevertSnapshotResponse.Merge(dst, src)
}
func (m *RevertSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_RevertSnapshotResponse.Size(m)
}
func (m *RevertSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevertSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevertSnapshotResponse proto.InternalMessageInfo

func (m *RevertSnapshotResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RevertSnapshotResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ChangeSnapshotNameRequest struct {
	Header               *v1.Header                         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Snap                 []*ChangeSnapshotNameRequest_Input `protobuf:"bytes,2,rep,name=snap,proto3" json:"snap,omitempty"`
	StopDc2              bool                               `protobuf:"varint,3,opt,name=stopDc2,proto3" json:"stopDc2,omitempty"`
	StartDc2             bool                               `protobuf:"varint,4,opt,name=startDc2,proto3" json:"startDc2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ChangeSnapshotNameRequest) Reset()         { *m = ChangeSnapshotNameRequest{} }
func (m *ChangeSnapshotNameRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeSnapshotNameRequest) ProtoMessage()    {}
func (*ChangeSnapshotNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{11}
}
func (m *ChangeSnapshotNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSnapshotNameRequest.Unmarshal(m, b)
}
func (m *ChangeSnapshotNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSnapshotNameRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeSnapshotNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSnapshotNameRequest.Merge(dst, src)
}
func (m *ChangeSnapshotNameRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeSnapshotNameRequest.Size(m)
}
func (m *ChangeSnapshotNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSnapshotNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSnapshotNameRequest proto.InternalMessageInfo

func (m *ChangeSnapshotNameRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ChangeSnapshotNameRequest) GetSnap() []*ChangeSnapshotNameRequest_Input {
	if m != nil {
		return m.Snap
	}
	return nil
}

func (m *ChangeSnapshotNameRequest) GetStopDc2() bool {
	if m != nil {
		return m.StopDc2
	}
	return false
}

func (m *ChangeSnapshotNameRequest) GetStartDc2() bool {
	if m != nil {
		return m.StartDc2
	}
	return false
}

type ChangeSnapshotNameRequest_Input struct {
	SnapUuid             string   `protobuf:"bytes,1,opt,name=snapUuid,proto3" json:"snapUuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeSnapshotNameRequest_Input) Reset()         { *m = ChangeSnapshotNameRequest_Input{} }
func (m *ChangeSnapshotNameRequest_Input) String() string { return proto.CompactTextString(m) }
func (*ChangeSnapshotNameRequest_Input) ProtoMessage()    {}
func (*ChangeSnapshotNameRequest_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{11, 0}
}
func (m *ChangeSnapshotNameRequest_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSnapshotNameRequest_Input.Unmarshal(m, b)
}
func (m *ChangeSnapshotNameRequest_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSnapshotNameRequest_Input.Marshal(b, m, deterministic)
}
func (dst *ChangeSnapshotNameRequest_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSnapshotNameRequest_Input.Merge(dst, src)
}
func (m *ChangeSnapshotNameRequest_Input) XXX_Size() int {
	return xxx_messageInfo_ChangeSnapshotNameRequest_Input.Size(m)
}
func (m *ChangeSnapshotNameRequest_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSnapshotNameRequest_Input.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSnapshotNameRequest_Input proto.InternalMessageInfo

func (m *ChangeSnapshotNameRequest_Input) GetSnapUuid() string {
	if m != nil {
		return m.SnapUuid
	}
	return ""
}

func (m *ChangeSnapshotNameRequest_Input) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChangeSnapshotNameResponse struct {
	Error                *v1.Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*v1.JobInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChangeSnapshotNameResponse) Reset()         { *m = ChangeSnapshotNameResponse{} }
func (m *ChangeSnapshotNameResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeSnapshotNameResponse) ProtoMessage()    {}
func (*ChangeSnapshotNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_snap_23ac0fddd7b4969d, []int{12}
}
func (m *ChangeSnapshotNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSnapshotNameResponse.Unmarshal(m, b)
}
func (m *ChangeSnapshotNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSnapshotNameResponse.Marshal(b, m, deterministic)
}
func (dst *ChangeSnapshotNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSnapshotNameResponse.Merge(dst, src)
}
func (m *ChangeSnapshotNameResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeSnapshotNameResponse.Size(m)
}
func (m *ChangeSnapshotNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSnapshotNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSnapshotNameResponse proto.InternalMessageInfo

func (m *ChangeSnapshotNameResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ChangeSnapshotNameResponse) GetData() []*v1.JobInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ListSnapshotRequest)(nil), "didi.cloud.compute.v1.ListSnapshotRequest")
	proto.RegisterType((*ListSnapshotCondition)(nil), "didi.cloud.compute.v1.ListSnapshotCondition")
	proto.RegisterType((*ListSnapshotResponse)(nil), "didi.cloud.compute.v1.ListSnapshotResponse")
	proto.RegisterType((*GetSnapshotTotalCntRequest)(nil), "didi.cloud.compute.v1.GetSnapshotTotalCntRequest")
	proto.RegisterType((*GetSnapshotTotalCntResponse)(nil), "didi.cloud.compute.v1.GetSnapshotTotalCntResponse")
	proto.RegisterType((*CreateSnapshotRequest)(nil), "didi.cloud.compute.v1.CreateSnapshotRequest")
	proto.RegisterType((*CreateSnapshotResponse)(nil), "didi.cloud.compute.v1.CreateSnapshotResponse")
	proto.RegisterType((*DeleteSnapshotRequest)(nil), "didi.cloud.compute.v1.DeleteSnapshotRequest")
	proto.RegisterType((*DeleteSnapshotRequest_Input)(nil), "didi.cloud.compute.v1.DeleteSnapshotRequest.Input")
	proto.RegisterType((*DeleteSnapshotResponse)(nil), "didi.cloud.compute.v1.DeleteSnapshotResponse")
	proto.RegisterType((*RevertSnapshotRequest)(nil), "didi.cloud.compute.v1.RevertSnapshotRequest")
	proto.RegisterType((*RevertSnapshotRequest_Input)(nil), "didi.cloud.compute.v1.RevertSnapshotRequest.Input")
	proto.RegisterType((*RevertSnapshotResponse)(nil), "didi.cloud.compute.v1.RevertSnapshotResponse")
	proto.RegisterType((*ChangeSnapshotNameRequest)(nil), "didi.cloud.compute.v1.ChangeSnapshotNameRequest")
	proto.RegisterType((*ChangeSnapshotNameRequest_Input)(nil), "didi.cloud.compute.v1.ChangeSnapshotNameRequest.Input")
	proto.RegisterType((*ChangeSnapshotNameResponse)(nil), "didi.cloud.compute.v1.ChangeSnapshotNameResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnapClient is the client API for Snap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnapClient interface {
	// 获取snap列表
	ListSnapshot(ctx context.Context, in *ListSnapshotRequest, opts ...grpc.CallOption) (*ListSnapshotResponse, error)
	// 获取snap数量
	GetSnapshotTotalCnt(ctx context.Context, in *GetSnapshotTotalCntRequest, opts ...grpc.CallOption) (*GetSnapshotTotalCntResponse, error)
	// 创建snap
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// 删除snap
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// 还原snap
	RevertSnapshot(ctx context.Context, in *RevertSnapshotRequest, opts ...grpc.CallOption) (*RevertSnapshotResponse, error)
	// 改名snap
	ChangeSnapshotName(ctx context.Context, in *ChangeSnapshotNameRequest, opts ...grpc.CallOption) (*ChangeSnapshotNameResponse, error)
}

type snapClient struct {
	cc *grpc.ClientConn
}

func NewSnapClient(cc *grpc.ClientConn) SnapClient {
	return &snapClient{cc}
}

func (c *snapClient) ListSnapshot(ctx context.Context, in *ListSnapshotRequest, opts ...grpc.CallOption) (*ListSnapshotResponse, error) {
	out := new(ListSnapshotResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Snap/ListSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapClient) GetSnapshotTotalCnt(ctx context.Context, in *GetSnapshotTotalCntRequest, opts ...grpc.CallOption) (*GetSnapshotTotalCntResponse, error) {
	out := new(GetSnapshotTotalCntResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Snap/GetSnapshotTotalCnt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Snap/CreateSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Snap/DeleteSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapClient) RevertSnapshot(ctx context.Context, in *RevertSnapshotRequest, opts ...grpc.CallOption) (*RevertSnapshotResponse, error) {
	out := new(RevertSnapshotResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Snap/RevertSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapClient) ChangeSnapshotName(ctx context.Context, in *ChangeSnapshotNameRequest, opts ...grpc.CallOption) (*ChangeSnapshotNameResponse, error) {
	out := new(ChangeSnapshotNameResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.compute.v1.Snap/ChangeSnapshotName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapServer is the server API for Snap service.
type SnapServer interface {
	// 获取snap列表
	ListSnapshot(context.Context, *ListSnapshotRequest) (*ListSnapshotResponse, error)
	// 获取snap数量
	GetSnapshotTotalCnt(context.Context, *GetSnapshotTotalCntRequest) (*GetSnapshotTotalCntResponse, error)
	// 创建snap
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// 删除snap
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// 还原snap
	RevertSnapshot(context.Context, *RevertSnapshotRequest) (*RevertSnapshotResponse, error)
	// 改名snap
	ChangeSnapshotName(context.Context, *ChangeSnapshotNameRequest) (*ChangeSnapshotNameResponse, error)
}

func RegisterSnapServer(s *grpc.Server, srv SnapServer) {
	s.RegisterService(&_Snap_serviceDesc, srv)
}

func _Snap_ListSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapServer).ListSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Snap/ListSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapServer).ListSnapshot(ctx, req.(*ListSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snap_GetSnapshotTotalCnt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotTotalCntRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapServer).GetSnapshotTotalCnt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Snap/GetSnapshotTotalCnt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapServer).GetSnapshotTotalCnt(ctx, req.(*GetSnapshotTotalCntRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snap_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Snap/CreateSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snap_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Snap/DeleteSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snap_RevertSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapServer).RevertSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Snap/RevertSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapServer).RevertSnapshot(ctx, req.(*RevertSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snap_ChangeSnapshotName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeSnapshotNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapServer).ChangeSnapshotName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.compute.v1.Snap/ChangeSnapshotName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapServer).ChangeSnapshotName(ctx, req.(*ChangeSnapshotNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Snap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didi.cloud.compute.v1.Snap",
	HandlerType: (*SnapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSnapshot",
			Handler:    _Snap_ListSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshotTotalCnt",
			Handler:    _Snap_GetSnapshotTotalCnt_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _Snap_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _Snap_DeleteSnapshot_Handler,
		},
		{
			MethodName: "RevertSnapshot",
			Handler:    _Snap_RevertSnapshot_Handler,
		},
		{
			MethodName: "ChangeSnapshotName",
			Handler:    _Snap_ChangeSnapshotName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute/v1/snap.proto",
}

func init() { proto.RegisterFile("compute/v1/snap.proto", fileDescriptor_snap_23ac0fddd7b4969d) }

var fileDescriptor_snap_23ac0fddd7b4969d = []byte{
	// 858 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x97, 0xbd, 0x6f, 0xfb, 0x44,
	0x18, 0xc7, 0x75, 0x79, 0xe9, 0xcb, 0x15, 0x31, 0x5c, 0x9b, 0x36, 0x75, 0x91, 0x9a, 0xba, 0x42,
	0x0d, 0x2f, 0xb1, 0x89, 0x8b, 0xe8, 0xc0, 0x46, 0xc2, 0x4b, 0x2b, 0x84, 0x90, 0x81, 0x0e, 0xa8,
	0xcb, 0xc5, 0xbe, 0x3a, 0x27, 0x92, 0x3b, 0xe3, 0x3b, 0x47, 0x2a, 0x42, 0x0c, 0x2c, 0x95, 0x98,
	0x90, 0x58, 0x90, 0x58, 0x98, 0x10, 0xe2, 0x2f, 0x60, 0xe2, 0x0f, 0x60, 0x65, 0x66, 0x63, 0x66,
	0xfe, 0x8d, 0x3f, 0xdd, 0xd9, 0x4e, 0xed, 0xfe, 0xec, 0x2a, 0x7d, 0x51, 0xa6, 0xe4, 0xf1, 0x3d,
	0x8f, 0xbf, 0xdf, 0xfb, 0xdc, 0xf9, 0x39, 0x1b, 0xb6, 0x3c, 0x3e, 0x0d, 0x63, 0x49, 0xec, 0x59,
	0xdf, 0x16, 0x0c, 0x87, 0x56, 0x18, 0x71, 0xc9, 0x51, 0xcb, 0xa7, 0x3e, 0xb5, 0xbc, 0x09, 0x8f,
	0x7d, 0x2b, 0xcd, 0xb0, 0x66, 0x7d, 0x03, 0x8d, 0xb0, 0xd0, 0xa9, 0xea, 0x37, 0x49, 0x35, 0x76,
	0x72, 0x77, 0xf0, 0xf8, 0x74, 0xca, 0x59, 0x3a, 0xf0, 0x4a, 0xc0, 0x79, 0x30, 0x21, 0x36, 0x0e,
	0xa9, 0x8d, 0x19, 0xe3, 0x12, 0x4b, 0xca, 0x99, 0x48, 0x46, 0xcd, 0x7f, 0x01, 0xdc, 0xfc, 0x98,
	0x0a, 0xf9, 0x19, 0xc3, 0xa1, 0x18, 0x73, 0xe9, 0x92, 0xaf, 0x63, 0x22, 0x24, 0x72, 0xe0, 0xca,
	0x98, 0x60, 0x9f, 0x44, 0x6d, 0xd0, 0x01, 0xdd, 0x0d, 0xc7, 0xb0, 0x72, 0x56, 0xb4, 0xec, 0xac,
	0x6f, 0x7d, 0xa4, 0x33, 0xdc, 0x34, 0x13, 0x6d, 0xc1, 0xa6, 0x90, 0x38, 0x92, 0xed, 0x5a, 0x07,
	0x74, 0x9b, 0x6e, 0x12, 0xa8, 0xab, 0x13, 0x3a, 0xa5, 0xb2, 0x5d, 0x4f, 0xae, 0xea, 0x00, 0x19,
	0x70, 0x4d, 0xd0, 0x69, 0x38, 0xa1, 0x97, 0x57, 0xed, 0x46, 0x07, 0x74, 0xd7, 0xdc, 0x79, 0x8c,
	0xce, 0xe0, 0xba, 0xc7, 0x99, 0x4f, 0x95, 0xcf, 0x76, 0x53, 0xcb, 0xbf, 0x69, 0x95, 0x92, 0xb0,
	0xf2, 0xd6, 0x07, 0x59, 0x8d, 0x7b, 0x53, 0x6e, 0x06, 0xb0, 0x55, 0x9a, 0x83, 0xda, 0x70, 0x95,
	0x8c, 0xc4, 0x17, 0x31, 0xf5, 0xf5, 0x0c, 0xd7, 0xdd, 0x2c, 0xd4, 0xd6, 0x18, 0x0e, 0x3f, 0xc1,
	0x53, 0xa2, 0x67, 0xb2, 0xee, 0xce, 0x63, 0x55, 0xe5, 0x7b, 0x8e, 0xae, 0xaa, 0x27, 0x55, 0x69,
	0x68, 0x7e, 0x0b, 0xb7, 0x8a, 0x1c, 0x45, 0xc8, 0x99, 0x20, 0xc8, 0x86, 0x4d, 0x12, 0x45, 0x3c,
	0xe3, 0xb8, 0x5b, 0xc6, 0xf1, 0x7d, 0x95, 0xe0, 0x26, 0x79, 0xe8, 0x18, 0x36, 0x7c, 0x2c, 0x71,
	0xbb, 0xd6, 0xa9, 0x77, 0x37, 0x9c, 0xfd, 0x8a, 0x89, 0x2b, 0x9d, 0x53, 0x76, 0xc9, 0x5d, 0x9d,
	0x6c, 0xfe, 0x0a, 0xa0, 0xf1, 0x21, 0x99, 0xab, 0x7f, 0xce, 0x25, 0x9e, 0x0c, 0xd8, 0xa3, 0x56,
	0x33, 0x07, 0xa8, 0x56, 0x0d, 0xa8, 0x5e, 0x0d, 0xa8, 0x51, 0x04, 0x74, 0x0d, 0xe0, 0x5e, 0xa9,
	0xc5, 0x87, 0x82, 0x3a, 0x29, 0x80, 0x3a, 0xac, 0x00, 0x95, 0xe9, 0xe4, 0x60, 0xfd, 0x02, 0x60,
	0x6b, 0x10, 0x11, 0x2c, 0xc9, 0x53, 0xec, 0xfa, 0xdc, 0x8c, 0x6b, 0x85, 0x19, 0xe7, 0x09, 0xd6,
	0xab, 0x09, 0x36, 0x8a, 0x04, 0xcd, 0x6f, 0xe0, 0xf6, 0x6d, 0x73, 0x0f, 0x25, 0x64, 0x17, 0x08,
	0xed, 0x95, 0xe5, 0x9f, 0xf1, 0x51, 0x8e, 0xcc, 0x9f, 0x00, 0xb6, 0x86, 0x64, 0x42, 0x9e, 0x86,
	0xcc, 0x07, 0xb0, 0xa1, 0x66, 0x95, 0xca, 0x3b, 0x15, 0x0b, 0x54, 0xaa, 0x67, 0x9d, 0xb2, 0x30,
	0x96, 0xae, 0xae, 0x37, 0x0e, 0x61, 0x53, 0x87, 0x19, 0xb6, 0xdc, 0x43, 0x3b, 0x8f, 0x15, 0xb6,
	0xdb, 0x77, 0x5a, 0x1a, 0xb6, 0xff, 0x01, 0x6c, 0xb9, 0x64, 0x46, 0x22, 0xb9, 0x3c, 0x6c, 0xa5,
	0x7a, 0x79, 0x6c, 0x6a, 0xfb, 0x09, 0xc9, 0xc3, 0xa1, 0xe7, 0xe8, 0xed, 0xb7, 0xe6, 0x66, 0xa1,
	0xe6, 0xa8, 0x7a, 0xb3, 0x1a, 0xca, 0x9a, 0x6f, 0x1a, 0x2f, 0x0c, 0xfb, 0xb6, 0xfe, 0xd2, 0x60,
	0xff, 0x50, 0x83, 0xbb, 0x83, 0x31, 0x66, 0xc1, 0x7c, 0xa5, 0xd5, 0x63, 0xf3, 0x18, 0xe0, 0x67,
	0x05, 0xe0, 0xef, 0x54, 0x00, 0xaf, 0xd4, 0x7c, 0x02, 0xe8, 0x27, 0x0b, 0x40, 0x47, 0x08, 0x36,
	0xd8, 0xcd, 0x99, 0xa4, 0xff, 0x9b, 0xdf, 0x41, 0xa3, 0xcc, 0xd7, 0xb2, 0x16, 0xc3, 0xf9, 0x6b,
	0x15, 0x36, 0x94, 0x34, 0xfa, 0x11, 0xc0, 0x97, 0xf2, 0xe7, 0x1f, 0x7a, 0x7d, 0x81, 0x13, 0x3b,
	0x05, 0x68, 0xbc, 0xb1, 0x50, 0x6e, 0x32, 0x29, 0xf3, 0xe8, 0xfb, 0x7f, 0xfe, 0xfb, 0xa9, 0x76,
	0x60, 0xee, 0xfb, 0x54, 0x17, 0xd8, 0xd4, 0x16, 0x92, 0x47, 0x38, 0x20, 0xfa, 0xcd, 0x49, 0xe5,
	0xda, 0x13, 0x2a, 0x24, 0xfa, 0x0d, 0xc0, 0xcd, 0x92, 0x03, 0x07, 0xf5, 0x2b, 0xd4, 0xaa, 0xcf,
	0x4f, 0xc3, 0xb9, 0x4f, 0x49, 0xea, 0xb3, 0xab, 0x7d, 0x9a, 0xa8, 0x73, 0x87, 0x4f, 0x8f, 0xc7,
	0x4c, 0xa2, 0x9f, 0x01, 0x7c, 0xb9, 0xd8, 0xf2, 0x51, 0xd5, 0xfb, 0x4e, 0xe9, 0xb1, 0x65, 0xf4,
	0x16, 0xcc, 0x4e, 0x9d, 0xbd, 0xa6, 0x9d, 0x1d, 0x9a, 0x07, 0x77, 0x38, 0xc3, 0x42, 0xd0, 0x80,
	0x69, 0x6b, 0xc5, 0xb6, 0x5a, 0x69, 0xad, 0xb4, 0x8f, 0x57, 0x5a, 0x2b, 0xef, 0xd5, 0x0b, 0x59,
	0xf3, 0x75, 0xa9, 0xb6, 0x56, 0x6c, 0x42, 0x95, 0xd6, 0x4a, 0x7b, 0x65, 0xa5, 0xb5, 0xf2, 0xce,
	0xb6, 0x90, 0xb5, 0x48, 0x97, 0xa2, 0xdf, 0x01, 0x44, 0x2f, 0x3e, 0x96, 0xe8, 0xad, 0xfb, 0x76,
	0x16, 0xa3, 0x7f, 0x8f, 0x8a, 0xd4, 0x66, 0x4f, 0xdb, 0x3c, 0x32, 0x5f, 0xbd, 0x6b, 0xdb, 0xe9,
	0x72, 0x55, 0xf6, 0xde, 0x35, 0x80, 0xdb, 0x1e, 0x9f, 0x6a, 0x9d, 0xab, 0x98, 0xe5, 0x44, 0x3e,
	0x05, 0x5f, 0xbe, 0x1d, 0x50, 0x39, 0x8e, 0x47, 0xea, 0xa2, 0x9d, 0x26, 0x64, 0xbf, 0xbd, 0x80,
	0xf7, 0x84, 0xff, 0x95, 0x7d, 0xf3, 0xd5, 0xf1, 0x6e, 0xfa, 0xf7, 0x19, 0x00, 0x7f, 0xd4, 0x76,
	0x86, 0xca, 0xf7, 0x30, 0xb1, 0x60, 0x0d, 0xd2, 0x9b, 0x9e, 0xf7, 0xff, 0x4e, 0x46, 0x2e, 0xd2,
	0x91, 0x8b, 0x74, 0xe4, 0xe2, 0xbc, 0x3f, 0x5a, 0xd1, 0x1f, 0x24, 0xc7, 0xcf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xf9, 0x56, 0x8f, 0x9f, 0x0b, 0x0d, 0x00, 0x00,
}
