// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor/v1/counter.proto

// dc2 Service
//
// dc2 Service API consists of a single service which returns
// a message.

package monitor

import (
	context "context"
	fmt "fmt"
	v1 "github.com/didiyun/didiyun-go-sdk/base/v1"
	_ "github.com/didiyun/didiyun-go-sdk/compute/v1"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCounterResponse struct {
	Error                *v1.Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*CounterOutput `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCounterResponse) Reset()         { *m = ListCounterResponse{} }
func (m *ListCounterResponse) String() string { return proto.CompactTextString(m) }
func (*ListCounterResponse) ProtoMessage()    {}
func (*ListCounterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{0}
}

func (m *ListCounterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCounterResponse.Unmarshal(m, b)
}
func (m *ListCounterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCounterResponse.Marshal(b, m, deterministic)
}
func (m *ListCounterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCounterResponse.Merge(m, src)
}
func (m *ListCounterResponse) XXX_Size() int {
	return xxx_messageInfo_ListCounterResponse.Size(m)
}
func (m *ListCounterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCounterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCounterResponse proto.InternalMessageInfo

func (m *ListCounterResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListCounterResponse) GetData() []*CounterOutput {
	if m != nil {
		return m.Data
	}
	return nil
}

type CounterOutput struct {
	ResourceUuid         string         `protobuf:"bytes,1,opt,name=resourceUuid,proto3" json:"resourceUuid,omitempty"`
	ResourceType         string         `protobuf:"bytes,2,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	Alias                string         `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Counters             []*CounterInfo `protobuf:"bytes,4,rep,name=counters,proto3" json:"counters,omitempty"`
	Metric               string         `protobuf:"bytes,5,opt,name=metric,proto3" json:"metric,omitempty"`
	MetricAlias          string         `protobuf:"bytes,6,opt,name=metricAlias,proto3" json:"metricAlias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CounterOutput) Reset()         { *m = CounterOutput{} }
func (m *CounterOutput) String() string { return proto.CompactTextString(m) }
func (*CounterOutput) ProtoMessage()    {}
func (*CounterOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{1}
}

func (m *CounterOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterOutput.Unmarshal(m, b)
}
func (m *CounterOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterOutput.Marshal(b, m, deterministic)
}
func (m *CounterOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterOutput.Merge(m, src)
}
func (m *CounterOutput) XXX_Size() int {
	return xxx_messageInfo_CounterOutput.Size(m)
}
func (m *CounterOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CounterOutput proto.InternalMessageInfo

func (m *CounterOutput) GetResourceUuid() string {
	if m != nil {
		return m.ResourceUuid
	}
	return ""
}

func (m *CounterOutput) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *CounterOutput) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CounterOutput) GetCounters() []*CounterInfo {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *CounterOutput) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *CounterOutput) GetMetricAlias() string {
	if m != nil {
		return m.MetricAlias
	}
	return ""
}

type CounterInfo struct {
	Dstype               string   `protobuf:"bytes,1,opt,name=dstype,proto3" json:"dstype,omitempty"`
	Step                 int32    `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	MonitorTags          string   `protobuf:"bytes,3,opt,name=monitorTags,proto3" json:"monitorTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CounterInfo) Reset()         { *m = CounterInfo{} }
func (m *CounterInfo) String() string { return proto.CompactTextString(m) }
func (*CounterInfo) ProtoMessage()    {}
func (*CounterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{2}
}

func (m *CounterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterInfo.Unmarshal(m, b)
}
func (m *CounterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterInfo.Marshal(b, m, deterministic)
}
func (m *CounterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterInfo.Merge(m, src)
}
func (m *CounterInfo) XXX_Size() int {
	return xxx_messageInfo_CounterInfo.Size(m)
}
func (m *CounterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CounterInfo proto.InternalMessageInfo

func (m *CounterInfo) GetDstype() string {
	if m != nil {
		return m.Dstype
	}
	return ""
}

func (m *CounterInfo) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *CounterInfo) GetMonitorTags() string {
	if m != nil {
		return m.MonitorTags
	}
	return ""
}

type ListCounterRequest struct {
	Header               *v1.Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Resource             []*CounterResource `protobuf:"bytes,2,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListCounterRequest) Reset()         { *m = ListCounterRequest{} }
func (m *ListCounterRequest) String() string { return proto.CompactTextString(m) }
func (*ListCounterRequest) ProtoMessage()    {}
func (*ListCounterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{3}
}

func (m *ListCounterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCounterRequest.Unmarshal(m, b)
}
func (m *ListCounterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCounterRequest.Marshal(b, m, deterministic)
}
func (m *ListCounterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCounterRequest.Merge(m, src)
}
func (m *ListCounterRequest) XXX_Size() int {
	return xxx_messageInfo_ListCounterRequest.Size(m)
}
func (m *ListCounterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCounterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCounterRequest proto.InternalMessageInfo

func (m *ListCounterRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ListCounterRequest) GetResource() []*CounterResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type CounterResource struct {
	ResourceUuids        []string `protobuf:"bytes,1,rep,name=resourceUuids,proto3" json:"resourceUuids,omitempty"`
	ResourceType         string   `protobuf:"bytes,2,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	Metric               []string `protobuf:"bytes,3,rep,name=metric,proto3" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CounterResource) Reset()         { *m = CounterResource{} }
func (m *CounterResource) String() string { return proto.CompactTextString(m) }
func (*CounterResource) ProtoMessage()    {}
func (*CounterResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{4}
}

func (m *CounterResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterResource.Unmarshal(m, b)
}
func (m *CounterResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterResource.Marshal(b, m, deterministic)
}
func (m *CounterResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterResource.Merge(m, src)
}
func (m *CounterResource) XXX_Size() int {
	return xxx_messageInfo_CounterResource.Size(m)
}
func (m *CounterResource) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterResource.DiscardUnknown(m)
}

var xxx_messageInfo_CounterResource proto.InternalMessageInfo

func (m *CounterResource) GetResourceUuids() []string {
	if m != nil {
		return m.ResourceUuids
	}
	return nil
}

func (m *CounterResource) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *CounterResource) GetMetric() []string {
	if m != nil {
		return m.Metric
	}
	return nil
}

type ListCounterDataRequest struct {
	Header               *v1.Header          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Counter              []*CounterDataInput `protobuf:"bytes,2,rep,name=counter,proto3" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListCounterDataRequest) Reset()         { *m = ListCounterDataRequest{} }
func (m *ListCounterDataRequest) String() string { return proto.CompactTextString(m) }
func (*ListCounterDataRequest) ProtoMessage()    {}
func (*ListCounterDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{5}
}

func (m *ListCounterDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCounterDataRequest.Unmarshal(m, b)
}
func (m *ListCounterDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCounterDataRequest.Marshal(b, m, deterministic)
}
func (m *ListCounterDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCounterDataRequest.Merge(m, src)
}
func (m *ListCounterDataRequest) XXX_Size() int {
	return xxx_messageInfo_ListCounterDataRequest.Size(m)
}
func (m *ListCounterDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCounterDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCounterDataRequest proto.InternalMessageInfo

func (m *ListCounterDataRequest) GetHeader() *v1.Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ListCounterDataRequest) GetCounter() []*CounterDataInput {
	if m != nil {
		return m.Counter
	}
	return nil
}

type CounterDataInput struct {
	ResourceType         string   `protobuf:"bytes,1,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	ResourceUuid         string   `protobuf:"bytes,2,opt,name=resourceUuid,proto3" json:"resourceUuid,omitempty"`
	MonitorTags          string   `protobuf:"bytes,3,opt,name=monitorTags,proto3" json:"monitorTags,omitempty"`
	Metric               string   `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	StartTime            int64    `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64    `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CounterDataInput) Reset()         { *m = CounterDataInput{} }
func (m *CounterDataInput) String() string { return proto.CompactTextString(m) }
func (*CounterDataInput) ProtoMessage()    {}
func (*CounterDataInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{6}
}

func (m *CounterDataInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterDataInput.Unmarshal(m, b)
}
func (m *CounterDataInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterDataInput.Marshal(b, m, deterministic)
}
func (m *CounterDataInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterDataInput.Merge(m, src)
}
func (m *CounterDataInput) XXX_Size() int {
	return xxx_messageInfo_CounterDataInput.Size(m)
}
func (m *CounterDataInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterDataInput.DiscardUnknown(m)
}

var xxx_messageInfo_CounterDataInput proto.InternalMessageInfo

func (m *CounterDataInput) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *CounterDataInput) GetResourceUuid() string {
	if m != nil {
		return m.ResourceUuid
	}
	return ""
}

func (m *CounterDataInput) GetMonitorTags() string {
	if m != nil {
		return m.MonitorTags
	}
	return ""
}

func (m *CounterDataInput) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *CounterDataInput) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CounterDataInput) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type ListCounterDataResponse struct {
	Error                *v1.Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*CounterDataOutput `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListCounterDataResponse) Reset()         { *m = ListCounterDataResponse{} }
func (m *ListCounterDataResponse) String() string { return proto.CompactTextString(m) }
func (*ListCounterDataResponse) ProtoMessage()    {}
func (*ListCounterDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{7}
}

func (m *ListCounterDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCounterDataResponse.Unmarshal(m, b)
}
func (m *ListCounterDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCounterDataResponse.Marshal(b, m, deterministic)
}
func (m *ListCounterDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCounterDataResponse.Merge(m, src)
}
func (m *ListCounterDataResponse) XXX_Size() int {
	return xxx_messageInfo_ListCounterDataResponse.Size(m)
}
func (m *ListCounterDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCounterDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCounterDataResponse proto.InternalMessageInfo

func (m *ListCounterDataResponse) GetError() *v1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListCounterDataResponse) GetData() []*CounterDataOutput {
	if m != nil {
		return m.Data
	}
	return nil
}

type CounterDataOutput struct {
	ResourceType         string              `protobuf:"bytes,1,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	MonitorTags          string              `protobuf:"bytes,2,opt,name=monitorTags,proto3" json:"monitorTags,omitempty"`
	Metric               string              `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	MetricAlias          string              `protobuf:"bytes,4,opt,name=metricAlias,proto3" json:"metricAlias,omitempty"`
	Values               []*CounterDataValue `protobuf:"bytes,5,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CounterDataOutput) Reset()         { *m = CounterDataOutput{} }
func (m *CounterDataOutput) String() string { return proto.CompactTextString(m) }
func (*CounterDataOutput) ProtoMessage()    {}
func (*CounterDataOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{8}
}

func (m *CounterDataOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterDataOutput.Unmarshal(m, b)
}
func (m *CounterDataOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterDataOutput.Marshal(b, m, deterministic)
}
func (m *CounterDataOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterDataOutput.Merge(m, src)
}
func (m *CounterDataOutput) XXX_Size() int {
	return xxx_messageInfo_CounterDataOutput.Size(m)
}
func (m *CounterDataOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterDataOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CounterDataOutput proto.InternalMessageInfo

func (m *CounterDataOutput) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *CounterDataOutput) GetMonitorTags() string {
	if m != nil {
		return m.MonitorTags
	}
	return ""
}

func (m *CounterDataOutput) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *CounterDataOutput) GetMetricAlias() string {
	if m != nil {
		return m.MetricAlias
	}
	return ""
}

func (m *CounterDataOutput) GetValues() []*CounterDataValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type CounterDataValue struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CounterDataValue) Reset()         { *m = CounterDataValue{} }
func (m *CounterDataValue) String() string { return proto.CompactTextString(m) }
func (*CounterDataValue) ProtoMessage()    {}
func (*CounterDataValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10d6d62cf52a45f, []int{9}
}

func (m *CounterDataValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterDataValue.Unmarshal(m, b)
}
func (m *CounterDataValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterDataValue.Marshal(b, m, deterministic)
}
func (m *CounterDataValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterDataValue.Merge(m, src)
}
func (m *CounterDataValue) XXX_Size() int {
	return xxx_messageInfo_CounterDataValue.Size(m)
}
func (m *CounterDataValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterDataValue.DiscardUnknown(m)
}

var xxx_messageInfo_CounterDataValue proto.InternalMessageInfo

func (m *CounterDataValue) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CounterDataValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*ListCounterResponse)(nil), "didi.cloud.monitor.v1.ListCounterResponse")
	proto.RegisterType((*CounterOutput)(nil), "didi.cloud.monitor.v1.CounterOutput")
	proto.RegisterType((*CounterInfo)(nil), "didi.cloud.monitor.v1.CounterInfo")
	proto.RegisterType((*ListCounterRequest)(nil), "didi.cloud.monitor.v1.ListCounterRequest")
	proto.RegisterType((*CounterResource)(nil), "didi.cloud.monitor.v1.CounterResource")
	proto.RegisterType((*ListCounterDataRequest)(nil), "didi.cloud.monitor.v1.ListCounterDataRequest")
	proto.RegisterType((*CounterDataInput)(nil), "didi.cloud.monitor.v1.CounterDataInput")
	proto.RegisterType((*ListCounterDataResponse)(nil), "didi.cloud.monitor.v1.ListCounterDataResponse")
	proto.RegisterType((*CounterDataOutput)(nil), "didi.cloud.monitor.v1.CounterDataOutput")
	proto.RegisterType((*CounterDataValue)(nil), "didi.cloud.monitor.v1.CounterDataValue")
}

func init() { proto.RegisterFile("monitor/v1/counter.proto", fileDescriptor_d10d6d62cf52a45f) }

var fileDescriptor_d10d6d62cf52a45f = []byte{
	// 749 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xd6, 0xe6, 0xaf, 0xed, 0x84, 0xaa, 0xb0, 0xb4, 0x8d, 0x89, 0x8a, 0x14, 0x59, 0x15, 0x04,
	0xa4, 0xda, 0x4a, 0xe0, 0x80, 0x04, 0x02, 0xf5, 0x07, 0x44, 0x25, 0x10, 0x68, 0x55, 0x7a, 0x80,
	0x5e, 0xb6, 0xf1, 0x92, 0x5a, 0xc4, 0x5e, 0xe3, 0x5d, 0x47, 0xea, 0x0d, 0xc1, 0x01, 0x0e, 0x95,
	0x38, 0x70, 0xe7, 0x01, 0x78, 0x14, 0xc4, 0x0d, 0x1e, 0x01, 0x89, 0x57, 0xe0, 0x88, 0xbc, 0xbb,
	0x69, 0xec, 0x24, 0xa4, 0x11, 0x9c, 0xec, 0x9d, 0xf9, 0x76, 0xe6, 0x9b, 0x6f, 0x66, 0x77, 0xc1,
	0x0a, 0x78, 0xe8, 0x4b, 0x1e, 0xbb, 0xfd, 0x96, 0xdb, 0xe1, 0x49, 0x28, 0x59, 0xec, 0x44, 0x31,
	0x97, 0x1c, 0xaf, 0x78, 0xbe, 0xe7, 0x3b, 0x9d, 0x1e, 0x4f, 0x3c, 0xc7, 0x80, 0x9c, 0x7e, 0xab,
	0x8e, 0x0f, 0xa9, 0x60, 0x29, 0x3a, 0xfd, 0x6a, 0x68, 0xbd, 0xd6, 0xe1, 0x41, 0x94, 0x48, 0xa6,
	0x83, 0x04, 0x01, 0x0f, 0x8d, 0x63, 0xad, 0xcb, 0x79, 0xb7, 0xc7, 0x5c, 0x1a, 0xf9, 0x2e, 0x0d,
	0x43, 0x2e, 0xa9, 0xf4, 0x79, 0x28, 0xb4, 0xd7, 0x7e, 0x83, 0xe0, 0xe2, 0x23, 0x5f, 0xc8, 0x6d,
	0x9d, 0x97, 0x30, 0x11, 0xf1, 0x50, 0x30, 0xec, 0x42, 0x99, 0xc5, 0x31, 0x8f, 0x2d, 0xd4, 0x40,
	0xcd, 0x6a, 0xfb, 0x92, 0x93, 0x61, 0xa2, 0xb2, 0xf6, 0x5b, 0xce, 0xfd, 0x14, 0x40, 0x34, 0x0e,
	0xdf, 0x82, 0x92, 0x47, 0x25, 0xb5, 0x0a, 0x8d, 0x62, 0xb3, 0xda, 0x5e, 0x77, 0x26, 0x32, 0x77,
	0x4c, 0x9a, 0x27, 0x89, 0x8c, 0x12, 0x49, 0xd4, 0x0e, 0xfb, 0x17, 0x82, 0xc5, 0x9c, 0x1d, 0xdb,
	0x70, 0x2e, 0x66, 0x82, 0x27, 0x71, 0x87, 0x3d, 0x4b, 0x7c, 0x4f, 0x71, 0x58, 0x20, 0x39, 0x5b,
	0x16, 0xb3, 0x77, 0x1c, 0x31, 0xab, 0x90, 0xc7, 0xa4, 0x36, 0xbc, 0x0c, 0x65, 0xda, 0xf3, 0xa9,
	0xb0, 0x8a, 0xca, 0xa9, 0x17, 0xf8, 0x2e, 0xcc, 0x1b, 0x95, 0x85, 0x55, 0x52, 0x6c, 0xed, 0xe9,
	0x6c, 0x77, 0xc3, 0x97, 0x9c, 0x9c, 0xee, 0xc1, 0xab, 0x50, 0x09, 0x98, 0x8c, 0xfd, 0x8e, 0x55,
	0x56, 0x61, 0xcd, 0x0a, 0x37, 0xa0, 0xaa, 0xff, 0x36, 0x55, 0xce, 0x8a, 0x72, 0x66, 0x4d, 0xf6,
	0x0b, 0xa8, 0x66, 0x42, 0xa6, 0x81, 0x3c, 0x21, 0x53, 0xf2, 0xba, 0x40, 0xb3, 0xc2, 0x18, 0x4a,
	0x42, 0xb2, 0x48, 0x95, 0x54, 0x26, 0xea, 0x5f, 0x05, 0xd7, 0xc4, 0xf6, 0x68, 0x77, 0x50, 0x50,
	0xd6, 0x64, 0x9f, 0x20, 0xc0, 0xb9, 0x4e, 0xbe, 0x4e, 0x98, 0x90, 0xb8, 0x0d, 0x95, 0x23, 0x46,
	0x3d, 0x36, 0xe8, 0x64, 0x7d, 0x52, 0x27, 0x1f, 0x2a, 0x04, 0x31, 0x48, 0xbc, 0x05, 0xf3, 0x03,
	0x1d, 0x4d, 0x3f, 0xaf, 0x4c, 0x57, 0x88, 0x18, 0x34, 0x39, 0xdd, 0x67, 0x0b, 0x58, 0x1a, 0x71,
	0xe2, 0x75, 0x58, 0xcc, 0xb6, 0x50, 0x58, 0xa8, 0x51, 0x6c, 0x2e, 0x90, 0xbc, 0x71, 0xa6, 0xc6,
	0x0e, 0x5b, 0x50, 0x54, 0x21, 0xcc, 0xca, 0xfe, 0x88, 0x60, 0x35, 0xa3, 0xc1, 0x0e, 0x95, 0xf4,
	0x7f, 0x74, 0xd8, 0x84, 0x39, 0xd3, 0x75, 0x23, 0xc3, 0xd5, 0xe9, 0x32, 0xa4, 0xf9, 0x76, 0xc3,
	0x74, 0xb2, 0x07, 0xfb, 0xec, 0x6f, 0x08, 0xce, 0x8f, 0x7a, 0xc7, 0x4a, 0x44, 0x13, 0x4a, 0x1c,
	0x3d, 0x03, 0x85, 0x09, 0x67, 0xe0, 0xcc, 0xa1, 0xc8, 0x08, 0x55, 0xca, 0xcd, 0xea, 0x1a, 0x2c,
	0x08, 0x49, 0x63, 0xb9, 0xe7, 0x07, 0x4c, 0x8d, 0x71, 0x91, 0x0c, 0x0d, 0xd8, 0x82, 0x39, 0x16,
	0x7a, 0xca, 0x57, 0x51, 0xbe, 0xc1, 0xd2, 0xfe, 0x80, 0xa0, 0x36, 0x26, 0xf0, 0xbf, 0x5e, 0x19,
	0x77, 0x72, 0x57, 0x46, 0xf3, 0x6c, 0x6d, 0x73, 0xd7, 0xc6, 0x0f, 0x04, 0x17, 0xc6, 0x7c, 0x33,
	0x49, 0x3b, 0x22, 0x5b, 0x61, 0x9a, 0x6c, 0xc5, 0x69, 0x47, 0xbc, 0x34, 0x76, 0xc4, 0xf1, 0x3d,
	0xa8, 0xf4, 0x69, 0x2f, 0x61, 0xc2, 0x2a, 0xcf, 0x3a, 0x31, 0xfb, 0x29, 0x9e, 0x98, 0x6d, 0xf6,
	0x83, 0xdc, 0xbc, 0x28, 0x5f, 0xda, 0x2d, 0xe9, 0x07, 0x4c, 0x48, 0x1a, 0x44, 0xaa, 0xa2, 0x22,
	0x19, 0x1a, 0xd2, 0x5b, 0x4e, 0xed, 0x55, 0x85, 0x20, 0xa2, 0x17, 0xed, 0xcf, 0x05, 0x98, 0x7b,
	0xac, 0xf3, 0xe1, 0x77, 0x08, 0xaa, 0x99, 0xae, 0xe1, 0x6b, 0x7f, 0x21, 0x35, 0x7e, 0x7d, 0xd4,
	0xaf, 0xcf, 0x02, 0xd5, 0x03, 0x60, 0x5f, 0x7e, 0xfb, 0xfd, 0xe7, 0xa7, 0x42, 0xcd, 0x5e, 0xf1,
	0x7c, 0x85, 0x77, 0x03, 0xf5, 0xe8, 0x98, 0xa3, 0x80, 0x4f, 0x10, 0x2c, 0x8d, 0xcc, 0x0e, 0xde,
	0x38, 0x3b, 0x7c, 0xe6, 0x10, 0xd7, 0x9d, 0x59, 0xe1, 0x86, 0x51, 0x5d, 0x31, 0x5a, 0xb6, 0x71,
	0x9e, 0x51, 0x3a, 0x3f, 0x5b, 0xef, 0x11, 0xac, 0x76, 0x78, 0xa0, 0x22, 0x1e, 0x27, 0x61, 0x26,
	0xdc, 0x53, 0xf4, 0xfc, 0x66, 0xd7, 0x97, 0x47, 0xc9, 0xa1, 0xd3, 0xe1, 0x81, 0x6b, 0x00, 0x83,
	0xef, 0x46, 0x97, 0x6f, 0x08, 0xef, 0x95, 0x3b, 0x7c, 0xb4, 0x6f, 0x9b, 0xdf, 0xdf, 0x08, 0x7d,
	0x29, 0xd4, 0x76, 0x52, 0x86, 0x3b, 0x3a, 0x9f, 0xb3, 0xad, 0x1f, 0x65, 0x67, 0xbf, 0xf5, 0x55,
	0x7b, 0x0e, 0x8c, 0xe7, 0xc0, 0xf4, 0xe6, 0x60, 0xbf, 0x75, 0x58, 0x51, 0x4f, 0xf1, 0x8d, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xa7, 0xa7, 0xab, 0x08, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	// 获取曲线列表
	ListCounter(ctx context.Context, in *ListCounterRequest, opts ...grpc.CallOption) (*ListCounterResponse, error)
	ListCounterData(ctx context.Context, in *ListCounterDataRequest, opts ...grpc.CallOption) (*ListCounterDataResponse, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) ListCounter(ctx context.Context, in *ListCounterRequest, opts ...grpc.CallOption) (*ListCounterResponse, error) {
	out := new(ListCounterResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.monitor.v1.Monitor/ListCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) ListCounterData(ctx context.Context, in *ListCounterDataRequest, opts ...grpc.CallOption) (*ListCounterDataResponse, error) {
	out := new(ListCounterDataResponse)
	err := c.cc.Invoke(ctx, "/didi.cloud.monitor.v1.Monitor/ListCounterData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	// 获取曲线列表
	ListCounter(context.Context, *ListCounterRequest) (*ListCounterResponse, error)
	ListCounterData(context.Context, *ListCounterDataRequest) (*ListCounterDataResponse, error)
}

// UnimplementedMonitorServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (*UnimplementedMonitorServer) ListCounter(ctx context.Context, req *ListCounterRequest) (*ListCounterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCounter not implemented")
}
func (*UnimplementedMonitorServer) ListCounterData(ctx context.Context, req *ListCounterDataRequest) (*ListCounterDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCounterData not implemented")
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_ListCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).ListCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.monitor.v1.Monitor/ListCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).ListCounter(ctx, req.(*ListCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_ListCounterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCounterDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).ListCounterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/didi.cloud.monitor.v1.Monitor/ListCounterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).ListCounterData(ctx, req.(*ListCounterDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "didi.cloud.monitor.v1.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCounter",
			Handler:    _Monitor_ListCounter_Handler,
		},
		{
			MethodName: "ListCounterData",
			Handler:    _Monitor_ListCounterData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor/v1/counter.proto",
}
